// AUTO-GENERATED by scripts/generate-route-mtimes.mjs — DO NOT EDIT.
// Regenerated by `npm run prebuild` (and `npm run generate:mtimes`).
// Provides per-URL lastModified for sitemap.xml so Google sees real freshness
// signal instead of "every page changed right now" on each sitemap regeneration.

export const routeMtimes: Record<string, string> = {
    "": "2026-05-18T18:24:28+02:00",
    "/o-nas": "2026-05-21T12:58:54+02:00",
    "/oferta": "2026-05-10T07:51:40+02:00",
    "/oferta/implantologia": "2026-05-21T12:58:54+02:00",
    "/oferta/leczenie-kanalowe": "2026-05-21T12:58:54+02:00",
    "/oferta/stomatologia-estetyczna": "2026-05-21T13:48:10+02:00",
    "/oferta/ortodoncja": "2026-05-21T14:50:08+02:00",
    "/oferta/chirurgia": "2026-05-21T14:50:08+02:00",
    "/oferta/protetyka": "2026-05-21T14:50:08+02:00",
    "/cennik": "2026-05-22T15:02:48+02:00",
    "/kontakt": "2026-05-21T22:14:07+02:00",
    "/rezerwacja": "2026-05-10T07:51:40+02:00",
    "/dla-pacjentow-przyjezdnych": "2026-05-21T22:14:07+02:00",
    "/aktualnosci": "2026-05-14T14:40:59+02:00",
    "/baza-wiedzy": "2026-05-10T07:51:40+02:00",
    "/metamorfozy": "2026-05-10T07:51:40+02:00",
    "/sklep": "2026-05-12T10:09:39+02:00",
    "/faq": "2026-05-10T07:51:40+02:00",
    "/nowosielski": "2026-05-10T17:32:20+02:00",
    "/mapa-bolu": "2026-05-10T07:51:40+02:00",
    "/kalkulator-leczenia": "2026-05-17T14:14:00+02:00",
    "/porownywarka": "2026-05-17T14:14:00+02:00",
    "/selfie": "2026-05-10T16:56:18+02:00",
    "/symulator": "2026-05-10T16:56:18+02:00",
    "/aplikacja": "2026-05-10T17:05:42+02:00",
    "/zadatek": "2026-05-09T15:51:16+02:00",
    "/regulamin": "2026-05-12T09:32:15+02:00",
    "/polityka-cookies": "2026-05-12T09:32:15+02:00",
    "/polityka-prywatnosci": "2026-05-17T21:43:41+02:00",
    "/rodo": "2026-05-12T09:32:15+02:00",
    "/privacy-policy": "2026-05-21T22:14:07+02:00"
};

/** Fallback for routes not in the map (e.g. newly added pages before next regen). */
export const buildTime: string = "2026-05-27T06:06:46.101Z";
