import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // S9 (2026-05-18): exclude generated/minified files from `public/` so they
    // don't pollute lint baseline. Autogenerated by next-pwa, pdfjs-dist,
    // firebase, etc. — never edited manually.
    "public/sw.js",
    "public/sw.js.map",
    "public/workbox-*.js",
    "public/workbox-*.js.map",
    "public/firebase-messaging-sw.js",
    "public/pdf.worker.min.mjs",
    "public/**/*.min.js",
    "public/**/*.min.mjs",
  ]),
]);

export default eslintConfig;
