-- Migration: 2-Stage SMS Reminder System
-- Purpose: Allow admin review and edit of SMS before sending
-- Date: 2026-02-06
-- Phase: Stage 1 - Generate drafts, Stage 2 - Admin review/send

-- Create sms_reminders table for draft storage
CREATE TABLE IF NOT EXISTS sms_reminders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Patient Info
    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    prodentis_id VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    
    -- Appointment Info (from Prodentis API 3.2)
    appointment_date TIMESTAMPTZ NOT NULL,
    appointment_end_date TIMESTAMPTZ,
    doctor_id INTEGER NOT NULL,
    doctor_name VARCHAR(255) NOT NULL,
    appointment_type VARCHAR(100) NOT NULL,
    
    -- SMS Content
    sms_message TEXT NOT NULL,
    template_used VARCHAR(50),
    
    -- Status Tracking
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'failed', 'cancelled')),
    sent_at TIMESTAMPTZ,
    sms_message_id VARCHAR(255),
    send_error TEXT,
    
    -- Admin Interaction
    edited_by VARCHAR(255),
    edited_at TIMESTAMPTZ,
    manually_sent_by VARCHAR(255),
    
    -- Audit
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Prevent duplicate SMS for same appointment
    UNIQUE(prodentis_id, appointment_date)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_sms_reminders_status 
    ON sms_reminders(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sms_reminders_date 
    ON sms_reminders(appointment_date);

CREATE INDEX IF NOT EXISTS idx_sms_reminders_patient 
    ON sms_reminders(patient_id);

-- Enable RLS
ALTER TABLE sms_reminders ENABLE ROW LEVEL SECURITY;

-- Admin-only access policy
CREATE POLICY admin_all_access ON sms_reminders
    FOR ALL
    USING (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE email LIKE '%@mikrostomart.pl'
        )
    );

-- Comments
COMMENT ON TABLE sms_reminders IS '2-stage SMS system: drafts generated by cron, reviewed by admin, then sent';
COMMENT ON COLUMN sms_reminders.status IS 'draft = pending review, sent = delivered, failed = send error, cancelled = admin deleted';
COMMENT ON COLUMN sms_reminders.sms_message IS 'Final SMS content - can be edited by admin';
COMMENT ON COLUMN sms_reminders.manually_sent_by IS 'Admin email if sent manually, NULL if auto-sent';
COMMENT ON COLUMN sms_reminders.template_used IS 'Which template generated this SMS (for analytics)';

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_sms_reminders_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sms_reminders_updated_at
    BEFORE UPDATE ON sms_reminders
    FOR EACH ROW
    EXECUTE FUNCTION update_sms_reminders_updated_at();
