import type { Metadata, Viewport } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { CartProvider } from "@/context/CartContext";
import { AssistantProvider } from "@/context/AssistantContext";
import { SimulatorProvider } from "@/context/SimulatorContext";
import { OpinionProvider } from "@/context/OpinionContext";
import { VisualEditorProvider } from "@/context/VisualEditorContext";
import ThemeLayout from "@/components/ThemeLayout";
import DemoBanner from "@/components/DemoBanner";
import CookieConsent from "@/components/CookieConsent";
import {
    AdminFloatingBarLazy,
    VisualEditorOverlayLazy,
    PageOverridesApplierLazy,
} from "@/components/AdminClientLayer";
import { isDemoMode } from "@/lib/demoMode";
import { brand, brandI18nParams, demoSanitize, loadBrandFromDB } from "@/lib/brandConfig";
import { fetchReviewSchemas, getAggregateRating, getAvailableServices, getOgLocale, hreflangCode, type AggregateRating } from "@/lib/seo";
import { formatPhoneForSchema } from "@/lib/phoneFormat";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-heading" });

export async function generateMetadata(): Promise<Metadata> {
    // Load brand from DB (falls back to hardcoded defaults on error)
    const b = await loadBrandFromDB();
    // J-4: dynamic og:locale per request — slug/listing pages without their
    // own pageMetadata() previously inherited the hardcoded pl_PL even on
    // /en/* and /de/* URLs. getLocale() reads the next-intl middleware's
    // resolved locale so the inherited tag matches the request.
    const locale = await getLocale();
    return {
        metadataBase: new URL(b.metadataBase),
        alternates: {
            canonical: './',
            // Per-page hreflang declared in each [locale]/<path>/layout.tsx via pageMetadata()
            // helper from @/lib/seo. Each public page now emits correct per-URL alternates
            // (e.g. /oferta → en:/en/oferta, de:/de/oferta, uk:/ua/oferta).
            // Root layout intentionally omits a global languages map — falsely declaring
            // every subpage's foreign-locale equivalent as the homepage was confusing Google.
            // Internal pages without per-page metadata (admin, pracownik) are disallowed in
            // robots.txt anyway, so they don't need hreflang.
        },
        title: {
            default: b.titleDefault,
            template: b.titleTemplate,
        },
        description: b.description,
        keywords: b.keywords,
        manifest: "/manifest.json",
        icons: {
            icon: '/icon.png',
            shortcut: '/icon.png',
            apple: '/icon-512x512.png',
        },
        openGraph: {
            type: 'website',
            locale: getOgLocale(locale),
            siteName: b.ogSiteName,
            // J-3: homepage-specific 1200×630 OG card (generated by
            // scripts/generate-og-images.mjs). Service pages override this
            // per-page via pageMetadata({ ogImage }); other inheriting pages
            // (FAQ, cennik, kontakt, etc.) fall back to og-home.
            images: [{
                url: '/og-home.webp',
                width: 1200,
                height: 630,
                alt: b.ogImageAlt,
            }],
        },
        twitter: {
            card: 'summary_large_image',
            images: ['/og-home.webp'],
        },
        other: isDemoMode ? undefined : {
            "geo.region": b.geoRegion,
            "geo.placename": b.geoPlacename,
            "geo.position": b.geoPosition,
            "ICBM": b.icbm,
            // J-5 follow-up #3 (2026-05-12): Business Suite domain claim. Uses
            // `name=` (different convention from fb:app_id below) which is what
            // Facebook's domain verification scanner explicitly looks for.
            ...(b.facebookDomainVerification ? { "facebook-domain-verification": b.facebookDomainVerification } : {}),
        },
        // NOTE on fb:app_id: Next.js `other` always emits `<meta name="…">`,
        // but Facebook's scraper only honours `<meta property="fb:app_id">`.
        // We render it manually in the <head> below — see RootLayout.
        appleWebApp: {
            capable: true,
            title: 'Mikrostomart',
            statusBarStyle: 'black-translucent',
        },
        applicationName: 'Mikrostomart',
    };
}

export const viewport: Viewport = {
    themeColor: "#0f1115",
};

function SchemaOrg({ aggregateRating, reviews, locale }: { aggregateRating: AggregateRating | null; reviews: Array<Record<string, unknown>>; locale: string }) {
    // Dentist schema with optional aggregateRating from Google Reviews (Faza G2)
    // and locale-aware availableService names + inLanguage (H4, 2026-05-10).
    // When ratings are available, SERP shows golden stars next to the result.
    const dentistSchema: Record<string, unknown> = {
        "@context": "https://schema.org",
        "@type": ["Dentist", "MedicalBusiness"],
        "name": brand.schemaName,
        "alternateName": brand.schemaAlternateName,
        "description": brand.schemaDescription,
        "image": brand.schemaImage,
        "@id": brand.schemaId,
        "url": brand.schemaUrl,
        "inLanguage": hreflangCode(locale),
        "telephone": isDemoMode ? undefined : formatPhoneForSchema(brand.phone1),
        // J-5 (2026-05-12): premium positioning signal. Mikrostomart targets
        // dental tourism (DE/EN/UA) where premium expectations are baseline —
        // M.Sc. RWTH Aachen + ZEISS microscope + Fotona laser justify $$$.
        // Strictly schema.org-internal; users never see this in SERP. Helps
        // Google match the clinic against "premium dental Poland" / "best
        // dentist Opole" / "high-end dental tourism" queries.
        "priceRange": "$$$",
        "currenciesAccepted": "PLN",
        "paymentAccepted": "Cash, Credit Card, BLIK, Apple Pay, Google Pay, Przelewy24, PayU",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": brand.streetAddress,
            "addressLocality": brand.city,
            "addressRegion": brand.region,
            "postalCode": brand.postalCode,
            "addressCountry": brand.country,
        },
        "geo": {
            "@type": "GeoCoordinates",
            "latitude": parseFloat(brand.geoPosition.split(';')[0]),
            "longitude": parseFloat(brand.geoPosition.split(';')[1]),
        },
        "hasMap": `https://www.google.com/maps/search/?api=1&query=${brand.mapQuery}`,
        // H8 (2026-05-10): full sameAs array — Google entity disambiguation.
        // Każdy URL musi prowadzić do tej samej entity (klinika/marka).
        "sameAs": [
            brand.facebookUrl,
            brand.instagramClinicUrl,
            brand.instagramDoctorUrl,
            brand.youtubeUrl,
            brand.googleBusinessUrl,
        ].filter(Boolean),
        "medicalSpecialty": [
            "Dentistry",
            "Endodontics",
            "Prosthodontics",
            "Orthodontics",
            "DentalHygiene"
        ],
        // Batch SEO-1 (2026-05-21): availableLanguage na klinice — strategiczne
        // dla DACH/EN dental tourism (Mikrostomart obsługuje pacjentów PL/EN/DE).
        // Person.availableLanguage Marcina dotyczy lekarza; klinika ma własną
        // (np. recepcja, Elżbieta — domyślnie PL, ale rozumiemy zapytania EN/DE).
        "availableLanguage": ["pl", "en", "de"],
        "availableService": getAvailableServices(locale),
        // L-3 (2026-05-21): locale-aware areaServed. Każda wersja językowa Dentist
        // schema sygnalizuje Google które rynki obsługujemy. DE locale rozszerzony
        // o Sachsen/Brandenburg/Berlin (border regions ~150-300 km od Opola) +
        // DACH countries = ranking boost dla "Zahnarzt Opole" w SERP DE z border.
        // EN locale: international/EU patients. UA locale: cross-border Ukraine.
        // PL locale: focus lokalny (Opole + województwo + Poland).
        "areaServed": (locale === 'de' ? [
            { "@type": "City", "name": "Opole" },
            { "@type": "Country", "name": "Poland" },
            { "@type": "Country", "name": "Germany" },
            { "@type": "AdministrativeArea", "name": "Sachsen" },
            { "@type": "AdministrativeArea", "name": "Brandenburg" },
            { "@type": "AdministrativeArea", "name": "Berlin" },
            { "@type": "Country", "name": "Austria" },
            { "@type": "Country", "name": "Switzerland" },
        ] : locale === 'en' ? [
            { "@type": "City", "name": "Opole" },
            { "@type": "Country", "name": "Poland" },
            { "@type": "Place", "name": "European Union" },
        ] : locale === 'ua' ? [
            { "@type": "City", "name": "Opole" },
            { "@type": "Country", "name": "Poland" },
            { "@type": "Country", "name": "Ukraine" },
        ] : [
            { "@type": "City", "name": "Opole" },
            { "@type": "AdministrativeArea", "name": "województwo opolskie" },
            { "@type": "Country", "name": "Poland" },
        ]),
        "openingHoursSpecification": [
            {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday"],
                "opens": "09:00",
                "closes": "20:00"
            },
            {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": "Friday",
                "opens": "09:00",
                "closes": "16:00"
            },
            {
                // Saturday is open on selected dates only ("wybrane terminy"),
                // so we deliberately omit a fixed Sat row to avoid misleading hours.
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": "Sunday",
                "opens": "00:00",
                "closes": "00:00"
            }
        ],
    };

    if (aggregateRating && aggregateRating.reviewCount > 0) {
        dentistSchema.aggregateRating = {
            "@type": "AggregateRating",
            ratingValue: aggregateRating.ratingValue,
            reviewCount: aggregateRating.reviewCount,
            bestRating: 5,
            worstRating: 1,
        };
    }

    // J-4 REVERTED (2026-05-23, GSC fix wariant D):
    // Embedded review[] removed from Dentist schema. GSC raport zgłosił 22
    // critical errors "Weryfikacja obejmuje wiele ocen zbiorczych" — Google
    // wykrywał konflikt między naszą schema (5.0★ / 23 reviews) a Google
    // Business Profile (4.5★ / 278 reviews). Plus embedded reviews z autorami
    // o własnym LocalBusiness łamią self-serving reviews policy.
    //
    // Reviews zostają widoczne w UI (GoogleReviews.tsx carousel na homepage)
    // — to OK, Google policy dotyczy tylko schema markup.
    //
    // aggregateRating ZACHOWANY ale teraz czyta z google_business_meta
    // (mig 135) wypełnianej przez cron z Google Places API authoritative
    // userRatingCount + rating. Zgodność schema ↔ GBP data → GSC happy.
    //
    // `reviews` prop nadal w signature dla backward compat (callers w
    // generateMetadata mogą przekazywać) — unused tutaj.
    void reviews;

    return (
        <>
            {/* Dentist / LocalBusiness schema */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify(dentistSchema)
                }}
            />
            {/* WebSite schema — multilingual signal + publisher entity disambiguation.
                SearchAction was removed: it pointed at /baza-wiedzy?q= which the page
                does not consume, so Google Rich Results Test flagged it broken.
                Re-add when /baza-wiedzy or another search endpoint actually handles ?q=. */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "WebSite",
                        "name": brand.name,
                        "url": brand.schemaUrl,
                        "inLanguage": ["pl", "en", "de", "uk"],
                        "publisher": {
                            "@type": "MedicalOrganization",
                            "name": brand.schemaName,
                            "url": brand.schemaUrl,
                            "logo": brand.schemaImage,
                        },
                    })
                }}
            />
        </>
    );
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Read locale from NEXT_LOCALE cookie (set by LanguageSwitcher)
    const locale = await getLocale();
    const rawMessages = await getMessages();

    // Fetch aggregate rating for Dentist schema (Faza G2).
    // Returns null in demo mode, on error, or when google_reviews table is empty.
    const aggregateRating = isDemoMode ? null : await getAggregateRating();
    // J-4: fetch top 10 positive reviews for embedding in Dentist.review[].
    // Same demo guard — demo deployment never serves prod reviews.
    const reviews = isDemoMode ? [] : await fetchReviewSchemas(10);

    // Recursively replace brand tokens ({brandName}, {cityShort}, etc.) in all translation strings.
    // next-intl v4 removed defaultTranslationValues from the provider, so we pre-bake them here.
    const brandParams = brandI18nParams();
    function deepBrandReplace(obj: any): any {
        if (typeof obj === 'string') {
            let s = obj;
            for (const [key, val] of Object.entries(brandParams)) {
                s = s.replaceAll(`{${key}}`, val);
            }
            return s;
        }
        if (Array.isArray(obj)) return obj.map(deepBrandReplace);
        if (obj && typeof obj === 'object') {
            const result: any = {};
            for (const key of Object.keys(obj)) result[key] = deepBrandReplace(obj[key]);
            return result;
        }
        return obj;
    }

    // Recursively sanitize all translation strings for demo mode
    function deepSanitize(obj: any): any {
        if (typeof obj === 'string') return demoSanitize(obj);
        if (Array.isArray(obj)) return obj.map(deepSanitize);
        if (obj && typeof obj === 'object') {
            const result: any = {};
            for (const key of Object.keys(obj)) result[key] = deepSanitize(obj[key]);
            return result;
        }
        return obj;
    }

    // Pipeline: replace brand tokens first, then sanitize for demo if needed
    const branded = deepBrandReplace(rawMessages);
    const messages = isDemoMode ? deepSanitize(branded) : branded;

    // S5-1 (2026-05-15): URL prefix 'ua' → ISO 639-1 'uk' (Ukrainian) for <html lang>.
    // Hreflang already maps via HREFLANG_MAP in sitemap.ts; html lang was the last
    // place still emitting non-standard 'ua'. Googlebot/screen readers expect 'uk'.
    const htmlLang = locale === 'ua' ? 'uk' : locale;

    return (
        <html lang={htmlLang}>
            <head>
                {/* J-5 follow-up #3: fb:app_id with property="" attribute (Facebook
                    only parses this form; Next.js Metadata API's `other` field
                    emits `name=""` which the FB Sharing Debugger ignores). Manual
                    head emit guarantees the correct attribute. */}
                {!isDemoMode && brand.facebookAppId && (
                    <meta property="fb:app_id" content={brand.facebookAppId} />
                )}
            </head>
            <body className={`${inter.variable} ${playfair.variable}`} style={isDemoMode ? { paddingTop: '2rem' } : undefined}>
                {/* Blocking script: Apply cached theme CSS vars BEFORE React hydrates to prevent flash */}
                <script dangerouslySetInnerHTML={{ __html: `
                    (function(){
                        try {
                            var c = null;
                            var raw = localStorage.getItem('densflow_theme');
                            if (raw) {
                                var t = JSON.parse(raw);
                                if (t && t.colors) c = t.colors;
                            }
                            ${isDemoMode ? `
                            if (!c) {
                                c = {background:'#FAFAFA',surface:'#FFFFFF',surfaceHover:'#F5F0EB',primary:'#9D7D5D',primaryLight:'#B89B7A',primaryDark:'#7A5F42',textMain:'#1A1A1A',textMuted:'#6B6B6B',success:'#22C55E',error:'#EF4444'};
                            }` : ''}
                            if (!c) return;
                            var r = document.documentElement.style;
                            function hexRgb(h) {
                                h = h.replace('#','');
                                return parseInt(h.substring(0,2),16)+','+parseInt(h.substring(2,4),16)+','+parseInt(h.substring(4,6),16);
                            }
                            if(c.background) r.setProperty('--color-background', c.background);
                            if(c.surface) r.setProperty('--color-surface', c.surface);
                            if(c.surfaceHover) r.setProperty('--color-surface-hover', c.surfaceHover);
                            if(c.primary) { r.setProperty('--color-primary', c.primary); r.setProperty('--color-primary-rgb', hexRgb(c.primary)); }
                            if(c.primaryLight) r.setProperty('--color-primary-light', c.primaryLight);
                            if(c.primaryDark) { r.setProperty('--color-primary-dark', c.primaryDark); r.setProperty('--color-primary-dark-rgb', hexRgb(c.primaryDark)); }
                            if(c.textMain) r.setProperty('--color-text-main', c.textMain);
                            if(c.textMuted) r.setProperty('--color-text-muted', c.textMuted);
                            if(c.success) r.setProperty('--color-success', c.success);
                            if(c.error) r.setProperty('--color-error', c.error);
                            // Faza G4: usunięte dodawanie splash-pending class — SplashScreen
                            // wyłączony globalnie, ta klasa już by jej nie zdejmowała.
                        } catch(e){}
                    })();
                ` }} />
                <DemoBanner />
                <SchemaOrg aggregateRating={aggregateRating} reviews={reviews} locale={locale} />
                {/* Faza G4: server-rendered cookie banner (czytanie HTTP cookie) — banner jest częścią initial paint, nie LCP-killing post-hydration insert. */}
                <CookieConsent />
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <VisualEditorProvider>
                        <CartProvider>
                            <AssistantProvider>
                                <SimulatorProvider>
                                    <OpinionProvider>
                                        <ThemeLayout>
                                            {children}
                                            <PageOverridesApplierLazy />
                                        </ThemeLayout>
                                    </OpinionProvider>
                                </SimulatorProvider>
                            </AssistantProvider>
                        </CartProvider>
                        <AdminFloatingBarLazy />
                        <VisualEditorOverlayLazy />
                    </VisualEditorProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
