import type { Method } from "./comparatorTypes";

export const METHODS_PERIO_DE: Record<string, Method> = {
    scaling: {
        id: "scaling", label: "Zahnsteinentfernung", short: "Professionelle Zahnsteinentfernung — Basis der Parodontgesundheit.",
        icon: "🧹", color: "#38bdf8", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "30–60 Min.", scale: 5, tooltip: "Ein Termin. Dauer abhängig von Zahnsteinmenge." },
            visits: { value: "1", scale: 5, tooltip: "In der Regel ein Termin." },
            durability: { value: "6–12 Monate", scale: 3, tooltip: "Zahnstein kehrt zurück — regelmäßige Besuche nötig." },
            invasiveness: { value: "Keine", scale: 5, tooltip: "Ultraschall + Handinstrumente. Kein Beschleifen." },
            risk: { value: "Keins", scale: 5, tooltip: "Vollkommen sicher. Vorübergehende Empfindlichkeit möglich." },
            hygiene: { value: "Keine Änderung", scale: 5, tooltip: "Standardpflege + Zahnseide." },
            worksWhen: ["Zahnstein- und Plaqueablagerungen", "Gingivitis (rotes, blutendes Zahnfleisch)", "Vor prothetischer oder kieferorthopädischer Behandlung"],
            notIdealWhen: ["Fortgeschrittene Parodontitis — tiefere Behandlung nötig", "Aktiver Abszess — erst Drainage", "Patient erwartet Heilung ohne Gewohnheitsänderung"],
            maintenance: { value: "Alle 6–12 Monate", tooltip: "Regelmäßige Besuche erhalten das Ergebnis." },
        },
        metrics: { durabilityScore: 40, speedScore: 92, minInvasiveScore: 100, maintenanceScore: 50, riskScore: 100 },
    },
    root_planing: {
        id: "root_planing", label: "Wurzelglättung (tiefe Reinigung)", short: "Tiefe Reinigung unterhalb des Zahnfleischrands — Taschenbehandlung.",
        icon: "🔍", color: "#f59e0b", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "2–4 Sitzungen", scale: 3, tooltip: "Quadrantenweise unter Anästhesie." },
            visits: { value: "2–4", scale: 3, tooltip: "Ein Quadrant pro Sitzung mit Anästhesie." },
            durability: { value: "Langfristig", scale: 4, tooltip: "Bei guter Hygiene: dauerhafte Taschenreduktion." },
            invasiveness: { value: "Gering–mittel", scale: 4, tooltip: "Subgingival, aber ohne Lappen." },
            risk: { value: "Gering", scale: 4, tooltip: "Vorübergehende Empfindlichkeit, mögliche Rezession." },
            hygiene: { value: "Entscheidend", scale: 2, tooltip: "Patient muss Gewohnheiten ändern. Interdentalreinigung essenziell." },
            worksWhen: ["Moderate Parodontitis (Taschen 4–6 mm)", "Erstbehandlung nach Diagnose", "Motivierter Patient mit Bereitschaft zur Hygieneänderung"],
            notIdealWhen: ["Taschen >6 mm — chirurgische Intervention ggf. nötig", "Fortgeschrittene Lockerung — Prognose schlecht", "Patient ändert Hygienegewohnheiten nicht"],
            maintenance: { value: "Reevaluation nach 6–8 Wochen", tooltip: "Taschennachmessung, Hygieneverstärkung." },
        },
        metrics: { durabilityScore: 65, speedScore: 62, minInvasiveScore: 72, maintenanceScore: 58, riskScore: 82 },
    },
    perio_surgery: {
        id: "perio_surgery", label: "Parodontalchirurgie", short: "Chirurgischer Zugang zur Tiefenreinigung.",
        icon: "🔪", color: "#dc2626", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–2 Stunden", scale: 2, tooltip: "Pro chirurgischem Segment." },
            visits: { value: "3–5", scale: 3, tooltip: "OP + Kontrollen + Nahtentfernung." },
            durability: { value: "Langfristig", scale: 4, tooltip: "Bei guter Hygiene: Knochenstabilisierung." },
            invasiveness: { value: "Hoch", scale: 2, tooltip: "Lappenoperation, Reinigung, ggf. Knochenaufbau." },
            risk: { value: "Mittel", scale: 3, tooltip: "Post-OP Schmerzen, Rezession, längere Heilung." },
            hygiene: { value: "Kritisch", scale: 2, tooltip: "Strenge Nachsorge und langfristiges Engagement." },
            worksWhen: ["Tiefe Taschen >6 mm nach Wurzelglättung nicht besser", "Knochenverlust erfordert Regeneration", "Erhaltenswerter Zahn mit guter Prognose"],
            notIdealWhen: ["Wurzelglättung ausreichend", "Patient pflegt nicht", "Zahn mit hoffnungsloser Prognose"],
            maintenance: { value: "Unterstützende Parodontaltherapie", tooltip: "Kontrollen alle 3–4 Monate anfangs." },
        },
        metrics: { durabilityScore: 72, speedScore: 38, minInvasiveScore: 18, maintenanceScore: 45, riskScore: 55 },
    },
    gum_graft: {
        id: "gum_graft", label: "Zahnfleischtransplantat", short: "Deckung freiliegender Wurzeln — Empfindlichkeit und Rezession beseitigen.",
        icon: "🌱", color: "#10b981", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–2 Stunden", scale: 3, tooltip: "Mikrochirurgischer Eingriff." },
            visits: { value: "2–3", scale: 3, tooltip: "OP + Kontrolle + Nahtentfernung." },
            durability: { value: "Langfristig", scale: 4, tooltip: "Gutes Ergebnis bei richtiger Hygiene." },
            invasiveness: { value: "Mittel", scale: 3, tooltip: "Entnahmestelle am Gaumen + Empfängerstelle." },
            risk: { value: "Mittel", scale: 3, tooltip: "Beschwerden an der Entnahmestelle, teilweises Transplantatversagen." },
            hygiene: { value: "Vorsichtig", scale: 3, tooltip: "Sanftes Putzen um das Transplantat." },
            worksWhen: ["Rezession mit Empfindlichkeit oder Ästhetikproblem", "Dünner gingivaler Biotyp mit progressiver Rezession", "Vor Prothetik — befestigte Gingiva nötig"],
            notIdealWhen: ["Sehr tiefe Rezession — eingeschränkte Deckung erwartet", "Aktive Parodontitis — erst behandeln", "Patient raucht — beeinträchtigt Heilung"],
            maintenance: { value: "Weiches Putzen + Kontrollen", tooltip: "Trauma vermeiden. Regelmäßige Nachsorge." },
        },
        metrics: { durabilityScore: 72, speedScore: 42, minInvasiveScore: 28, maintenanceScore: 62, riskScore: 58 },
    },
    supportive_perio: {
        id: "supportive_perio", label: "Unterstützende Parodontaltherapie", short: "Regelmäßige Nachsorge — Schlüssel zum Langzeiterfolg.",
        icon: "🔄", color: "#06b6d4", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "30–45 Min.", scale: 5, tooltip: "Prophylaxe + Taschenbeurteilung." },
            visits: { value: "3–4×/Jahr", scale: 2, tooltip: "Anfangs alle 3–4 Monate." },
            durability: { value: "Fortlaufend", scale: 5, tooltip: "Kontinuierliche Unterstützung des behandelten Parodonts." },
            invasiveness: { value: "Keine", scale: 5, tooltip: "Nicht-invasive Erhaltung." },
            risk: { value: "Keins", scale: 5, tooltip: "Sichere, präventive Maßnahme." },
            hygiene: { value: "Essenziell", scale: 2, tooltip: "Patient muss häusliche Pflege beibehalten." },
            worksWhen: ["Nach aktiver Parodontalbehandlung", "Patient möchte Ergebnis erhalten", "Stabile, aber betreute Parodontitis"],
            notIdealWhen: ["Keine Vorbehandlung — kein Ersatz für aktive Therapie", "Nicht-kooperativer Patient", "Aktive Erkrankung braucht erst Behandlung"],
            maintenance: { value: "Fortlaufend 3–4×/Jahr", tooltip: "Lebenslange Betreuung für Bestresultat." },
        },
        metrics: { durabilityScore: 82, speedScore: 85, minInvasiveScore: 100, maintenanceScore: 35, riskScore: 100 },
    },
};
