import type { Method } from "./comparatorTypes";

export const METHODS_ESTETYKA_UA: Record<string, Method> = {
    whitening: {
        id: "whitening", label: "Відбілювання", short: "Зміна кольору без втручання у структуру зуба.",
        icon: "🦷", color: "#fbbf24", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "1–14 днів", scale: 5, tooltip: "Кабінетне: 1 візит. Капи: 7–14 днів вдома." },
            visits: { value: "1–2", scale: 5, tooltip: "Один кабінетний візит або видача кап + контроль." },
            durability: { value: "Середня", scale: 2, tooltip: "Ефект 1–3 роки залежно від харчування та гігієни. Потрібне повторення." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Жодного втручання у структуру зуба." },
            risk: { value: "Низький", scale: 5, tooltip: "Тимчасова чутливість. Не для оголених шийок." },
            hygiene: { value: "Без змін", scale: 5, tooltip: "Стандартна гігієна; уникайте барвних продуктів перші дні." },
            worksWhen: ["Бажаєте світліший відтінок без обточування", "Зуби здорові та рівні", "Проблема лише в кольорі"],
            notIdealWhen: ["Є пломби в зоні усмішки — вони не відбіляться", "Проблема у формі, а не в кольорі", "Сильна чутливість зубів"],
            maintenance: { value: "Оновлення кожні 1–2 роки", tooltip: "Домашнє або кабінетне оновлення." },
        },
        metrics: { durabilityScore: 25, speedScore: 90, minInvasiveScore: 100, maintenanceScore: 60, riskScore: 92 },
    },
    bonding_smile: {
        id: "bonding_smile", label: "Бондинг", short: "Пряма реставрація композитом — швидка, консервативна, зворотна.",
        icon: "🖌️", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 день – 2 тиж.", scale: 5, tooltip: "Простий бондинг 1–2 зуби: 1 візит. Ширший обсяг: 2–3 сеанси." },
            visits: { value: "1–3", scale: 5, tooltip: "Часто за один візит. При 6+ зубах: план + сеанси." },
            durability: { value: "Середня", scale: 3, tooltip: "3–7 років. Композит може забарвитись; потрібне полірування." },
            invasiveness: { value: "Дуже низька", scale: 5, tooltip: "Мінімальне або нульове обточування — матеріал додається." },
            risk: { value: "Низький", scale: 5, tooltip: "Зворотна процедура. Ризик: зміна кольору або відколи." },
            hygiene: { value: "Легка", scale: 5, tooltip: "Як власні зуби — звичайне чищення та нитка." },
            worksWhen: ["Дрібні корекції форми, відколи, малі діастеми", "Бажаєте швидко й без обточування", "Хочете протестувати зміну перед вінірами"],
            notIdealWhen: ["Великі зміни кольору всієї дуги", "Бруксизм без шини", "Очікуєте 10+ років без обслуговування"],
            maintenance: { value: "Полірування 1–2×/рік", tooltip: "Просте полірування + дрібні виправлення." },
        },
        metrics: { durabilityScore: 45, speedScore: 95, minInvasiveScore: 95, maintenanceScore: 70, riskScore: 90 },
    },
    veneer_porc_smile: {
        id: "veneer_porc_smile", label: "Порцелянові вініри", short: "Довговічні, стійкі до забарвлення — золотий стандарт естетики.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "2–4 тижні", scale: 3, tooltip: "Препарація + скан → лабораторія → фіксація." },
            visits: { value: "2–4", scale: 3, tooltip: "План, препарація, примірка, цементування." },
            durability: { value: "Висока", scale: 5, tooltip: "Порцеляна не змінює колір. Термін служби 10–20 років." },
            invasiveness: { value: "Середня", scale: 3, tooltip: "Зняття 0,3–0,7 мм емалі. Незворотно." },
            risk: { value: "Середній", scale: 3, tooltip: "Незворотне обточування. Ризик перелому при бруксизмі." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Порцеляна гладка — легко чистити." },
            worksWhen: ["Повне перетворення усмішки 8–10 зубів", "Значна зміна кольору та форми", "Пріоритет — довговічність на роки"],
            notIdealWhen: ["Не бажаєте обточувати зуби", "Корекція 1–2 зубів — бондингу достатньо", "Дуже тонка емаль"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Оцінка цементування, перевірка зубів під вінірами." },
        },
        metrics: { durabilityScore: 88, speedScore: 55, minInvasiveScore: 50, maintenanceScore: 78, riskScore: 60 },
    },
    crown_smile: {
        id: "crown_smile", label: "Коронка", short: "Повне покриття зуба — відбудова + зміцнення + естетика.",
        icon: "👑", color: "#38bdf8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–14 днів", scale: 4, tooltip: "Препарація + скан → лабораторія → фіксація." },
            visits: { value: "2–3", scale: 4, tooltip: "Препарація, примірка, встановлення." },
            durability: { value: "Висока", scale: 5, tooltip: "Керамічна коронка: 10–20 років. Захищає ослаблений зуб." },
            invasiveness: { value: "Висока", scale: 1, tooltip: "Значне обточування зуба з усіх боків." },
            risk: { value: "Середній", scale: 3, tooltip: "Потрібна оцінка вітальності. Іноді спочатку ендо." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Як власний зуб — стандартна гігієна." },
            worksWhen: ["Сильно зруйнований зуб (після ендо, великі каверни)", "Потрібне зміцнення + естетика", "Бруксизм — коронка стійка"],
            notIdealWhen: ["Зуб здоровий — вінір або бондинг достатньо", "Бажаєте зберегти максимум тканин", "Проблема лише кольору — розгляньте відбілювання"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Перевірка герметичності країв, контрольний знімок." },
        },
        metrics: { durabilityScore: 85, speedScore: 70, minInvasiveScore: 20, maintenanceScore: 75, riskScore: 55 },
    },
    veneer_comp_type: {
        id: "veneer_comp_type", label: "Композитні вініри", short: "Швидше й менш інвазивно, але потребують обслуговування.",
        icon: "🪞", color: "#f59e0b", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1–7 днів", scale: 5, tooltip: "Без лабораторного етапу. Часто за 1–2 візити." },
            visits: { value: "1–2", scale: 5, tooltip: "План + лікувальний сеанс." },
            durability: { value: "Середня", scale: 3, tooltip: "3–7 років. Можуть забарвитись; потрібне полірування." },
            invasiveness: { value: "Низька", scale: 4, tooltip: "Мінімальне обточування — менше, ніж при порцеляні." },
            risk: { value: "Низький", scale: 4, tooltip: "Менша довговічність, але процедура зворотна." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Стандартна гігієна. Уникайте твердої їжі." },
            worksWhen: ["Бажаєте швидкий результат без очікування лабораторії", "Компроміс: краще за бондинг, менш інвазивно ніж порцеляна", "Корекція діастем і форми"],
            notIdealWhen: ["Очікуєте 10+ років довговічності", "Бруксизм", "Повне перетворення 8–10 зубів"],
            maintenance: { value: "Полірування 1–2×/рік", tooltip: "Полірування та оцінка стану." },
        },
        metrics: { durabilityScore: 50, speedScore: 88, minInvasiveScore: 80, maintenanceScore: 65, riskScore: 82 },
    },
    veneer_porc_type: {
        id: "veneer_porc_type", label: "Порцелянові вініри", short: "Довговічні, стійкі до забарвлення, преміум — потребують лабораторії.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "2–4 тижні", scale: 3, tooltip: "Препарація → лабораторія → встановлення." },
            visits: { value: "2–4", scale: 3, tooltip: "Препарація, скан, примірка, цементування." },
            durability: { value: "Висока", scale: 5, tooltip: "10–20 років. Колір стабільний, не забарвлюється." },
            invasiveness: { value: "Середня", scale: 3, tooltip: "Обточування 0,3–0,7 мм. Незворотно." },
            risk: { value: "Середній", scale: 3, tooltip: "Незворотне обточування. Потрібна шина при бруксизмі." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Гладка порцеляна — легко доглядати." },
            worksWhen: ["Пріоритет: довговічність і стабільність кольору", "Повне перетворення усмішки", "Значні зміни форми та пропорцій"],
            notIdealWhen: ["Шукаєте швидке рішення", "Не приймаєте обточування", "Корекція 1–2 зубів"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Оцінка цементування та стану основи." },
        },
        metrics: { durabilityScore: 88, speedScore: 50, minInvasiveScore: 50, maintenanceScore: 78, riskScore: 60 },
    },
    bonding_spot: {
        id: "bonding_spot", label: "Точковий бондинг (1–2 зуби)", short: "Швидка корекція одного-двох зубів за один візит.",
        icon: "✏️", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 візит", scale: 5, tooltip: "Уся процедура за одну коротку зустріч." },
            visits: { value: "1", scale: 5, tooltip: "Одноразовий сеанс 30–60 хв." },
            durability: { value: "Середня", scale: 3, tooltip: "3–7 років. Дрібні ремонти легкі." },
            invasiveness: { value: "Мінімальна", scale: 5, tooltip: "Нульове або мінімальне обточування." },
            risk: { value: "Дуже низький", scale: 5, tooltip: "Повністю зворотна. Легко ремонтується." },
            hygiene: { value: "Без змін", scale: 5, tooltip: "Як власні зуби." },
            worksWhen: ["Відколений ріжок, дрібна нерівність", "Мала діастема між 1–2 зубами", "Бажаєте швидко й недорого протестувати зміну"],
            notIdealWhen: ["Проблема стосується 4+ зубів", "Бажаєте змінити колір усієї дуги", "Очікуєте багаторічної довговічності"],
            maintenance: { value: "Полірування 1×/рік", tooltip: "Швидке полірування на контролі." },
        },
        metrics: { durabilityScore: 45, speedScore: 98, minInvasiveScore: 98, maintenanceScore: 75, riskScore: 95 },
    },
    bonding_full: {
        id: "bonding_full", label: "Бондинг повної дуги (6–10 зубів)", short: "Комплексна зміна усмішки композитом — без лабораторії.",
        icon: "😁", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–3 тижні", scale: 4, tooltip: "Планування + 2–3 лікувальні сеанси." },
            visits: { value: "2–4", scale: 4, tooltip: "План (DSD/mock-up) + сеанси по 3–5 зубів." },
            durability: { value: "Середня", scale: 3, tooltip: "3–7 років. Потрібне регулярне обслуговування." },
            invasiveness: { value: "Низька", scale: 4, tooltip: "Мінімальне обточування, але багато роботи." },
            risk: { value: "Низький", scale: 4, tooltip: "Зворотна. Ризик: нерівномірне забарвлення через роки." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Стандартна гігієна. Полірування підтримує гладкість." },
            worksWhen: ["Бажаєте метаморфозу без обточування", "Альтернатива порцеляновим вінірам", "Бажаєте протестувати нову форму усмішки"],
            notIdealWhen: ["Бруксизм без шини", "Очікуєте 10+ років без обслуговування", "Дуже великі зміни кольору"],
            maintenance: { value: "Полірування 2×/рік", tooltip: "Регулярне полірування та перевірка країв." },
        },
        metrics: { durabilityScore: 45, speedScore: 80, minInvasiveScore: 85, maintenanceScore: 60, riskScore: 82 },
    },
    aligners: {
        id: "aligners", label: "Ортодонтія (елайнери)", short: "Вирівнювання зубів капами — лікування причини, а не маскування.",
        icon: "🔄", color: "#06b6d4", recommendedSpecialist: "marcin",
        table: {
            time: { value: "6–18 місяців", scale: 1, tooltip: "Залежить від складності випадку." },
            visits: { value: "6–12", scale: 1, tooltip: "Контроль кожні 4–6 тижнів." },
            durability: { value: "Постійна", scale: 5, tooltip: "Тривалий результат при носінні ретейнера." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Жодного обточування. Біологічний рух." },
            risk: { value: "Низький", scale: 4, tooltip: "Потрібна дисципліна (20+ год/день). Можлива резорбція коренів." },
            hygiene: { value: "Потрібна рутина", scale: 3, tooltip: "Знімати для їжі, чистити капи." },
            worksWhen: ["Скупченість, ротації, нерівності", "Бажаєте лікувати причину, а не маскувати", "Діастеми через позицію зубів"],
            notIdealWhen: ["Бажаєте ефект за кілька днів", "Проблема в кольорі, а не позиції", "Не будете носити капи 20+ год/день"],
            maintenance: { value: "Фіксований/знімний ретейнер", tooltip: "Ретейнер після лікування — ключ до збереження результату." },
        },
        metrics: { durabilityScore: 92, speedScore: 15, minInvasiveScore: 95, maintenanceScore: 55, riskScore: 78 },
    },
    bonding_mask: {
        id: "bonding_mask", label: "Бондинг / Вініри", short: "Маскування нерівностей — швидше, але не лікує причину.",
        icon: "🎭", color: "#f59e0b", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1–14 днів", scale: 5, tooltip: "Бондинг: 1 візит. Вініри: 1–2 тижні." },
            visits: { value: "1–3", scale: 5, tooltip: "План + лікувальний сеанс." },
            durability: { value: "Середня", scale: 3, tooltip: "3–10 років залежно від матеріалу й обсягу." },
            invasiveness: { value: "Низька–середня", scale: 4, tooltip: "Бондинг: мінімальна. Вініри: обточування." },
            risk: { value: "Низький", scale: 4, tooltip: "Маскування, а не корекція позиції." },
            hygiene: { value: "Легка", scale: 5, tooltip: "Стандартна гігієна." },
            worksWhen: ["Дрібні естетичні нерівності", "Бажаєте швидкий ефект", "Не приймаєте тривале ортодонтичне лікування"],
            notIdealWhen: ["Значна скупченість — немає місця для матеріалу", "Проблеми прикусу, що впливають на функцію", "Бажаєте тривале причинне рішення"],
            maintenance: { value: "Обслуговування 1–2×/рік", tooltip: "Полірування бондингу або контроль вінірів." },
        },
        metrics: { durabilityScore: 50, speedScore: 90, minInvasiveScore: 75, maintenanceScore: 70, riskScore: 82 },
    },
    bonding_dia: {
        id: "bonding_dia", label: "Бондинг", short: "Закриття діастеми композитом — швидке та зворотне.",
        icon: "🖌️", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 візит", scale: 5, tooltip: "Швидке закриття проміжку за один сеанс." },
            visits: { value: "1", scale: 5, tooltip: "Уся процедура за одну зустріч." },
            durability: { value: "Середня", scale: 3, tooltip: "3–7 років. Може потребувати коригувань." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Без обточування." },
            risk: { value: "Дуже низький", scale: 5, tooltip: "Повністю зворотна." },
            hygiene: { value: "Легка", scale: 5, tooltip: "Нитка потребує обережності біля країв." },
            worksWhen: ["Мала діастема (1–2 мм)", "Бажаєте швидкий результат", "Хочете протестувати перед вінірами"],
            notIdealWhen: ["Велика діастема (>3 мм) — може виглядати неприродно", "Діастема повертається через позицію зубів", "Бруксизм"],
            maintenance: { value: "Полірування 1×/рік", tooltip: "Перевірка країв і полірування." },
        },
        metrics: { durabilityScore: 45, speedScore: 98, minInvasiveScore: 98, maintenanceScore: 72, riskScore: 92 },
    },
    ortho_dia: {
        id: "ortho_dia", label: "Ортодонтія", short: "Закриття діастеми рухом зубів — назавжди, але довго.",
        icon: "🔄", color: "#06b6d4", recommendedSpecialist: "marcin",
        table: {
            time: { value: "3–12 місяців", scale: 2, tooltip: "Залежить від розміру проміжку й співпраці." },
            visits: { value: "4–8", scale: 2, tooltip: "Контроль кожні 4–6 тижнів." },
            durability: { value: "Постійна", scale: 5, tooltip: "Тривалий результат при ретейнері." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Біологічний рух, без обточування." },
            risk: { value: "Низький", scale: 4, tooltip: "Потрібен ретейнер; інакше діастема може повернутися." },
            hygiene: { value: "Потрібна рутина", scale: 3, tooltip: "Чищення з апаратом потребує дисципліни." },
            worksWhen: ["Діастема через позицію зубів", "Бажаєте тривале причинне рішення", "Інші нерівності теж потребують корекції"],
            notIdealWhen: ["Бажаєте миттєвий ефект", "Діастема через пропорції зубів (занадто вузькі)", "Не приймаєте тривале лікування"],
            maintenance: { value: "Ретейнер після лікування", tooltip: "Фіксований або знімний ретейнер — обов'язковий." },
        },
        metrics: { durabilityScore: 90, speedScore: 20, minInvasiveScore: 95, maintenanceScore: 55, riskScore: 78 },
    },
    veneer_dia: {
        id: "veneer_dia", label: "Вініри", short: "Закриття діастеми вінірами — довговічне з миттєвим ефектом.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–3 тижні", scale: 4, tooltip: "Композитні: 1–3 дні. Порцелянові: 2–3 тижні." },
            visits: { value: "1–3", scale: 4, tooltip: "Залежить від матеріалу й обсягу." },
            durability: { value: "Середньо-висока", scale: 4, tooltip: "Композитні: 5–7 років. Порцелянові: 10–20 років." },
            invasiveness: { value: "Низька–середня", scale: 3, tooltip: "Композитні: мінімальна. Порцелянові: обточування." },
            risk: { value: "Низький–середній", scale: 4, tooltip: "Порцелянові незворотні." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Стандартна гігієна + нитка." },
            worksWhen: ["Діастема через пропорції зубів", "Бажаєте одночасно покращити форму", "Шукаєте тривалий косметичний результат"],
            notIdealWhen: ["Діастема через позицію — краще ортодонтія", "Дуже великий проміжок (>4 мм)", "Не бажаєте обточування"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Полірування (композит) або перевірка (порцеляна)." },
        },
        metrics: { durabilityScore: 72, speedScore: 75, minInvasiveScore: 55, maintenanceScore: 72, riskScore: 72 },
    },
    splint_rebuild: {
        id: "splint_rebuild", label: "Шина + відбудови", short: "Захист від подальшого стирання + відновлення втрачених тканин.",
        icon: "🛡️", color: "#10b981", recommendedSpecialist: "ilona",
        table: {
            time: { value: "1–3 тижні", scale: 4, tooltip: "Шина: 1–2 візити. Композитні відбудови: 1–3 сеанси." },
            visits: { value: "2–4", scale: 4, tooltip: "Шина + сеанси відбудови." },
            durability: { value: "Середня", scale: 3, tooltip: "Відбудови потребують обслуговування. Шина: довговічна при носінні." },
            invasiveness: { value: "Низька", scale: 5, tooltip: "Адитивні відбудови; шина неінвазивна." },
            risk: { value: "Низький", scale: 5, tooltip: "Найбезпечніший підхід — захищає решту зубів." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Шину чистити, зуби як зазвичай." },
            worksWhen: ["Ранні та помірні стирання", "Підтверджений бруксизм", "Бажаєте захистити зуби й поступово відбудувати"],
            notIdealWhen: ["Виражене стирання потребує повного покриття", "Не носите шину регулярно", "Пріоритет — негайна естетична зміна"],
            maintenance: { value: "Нічна шина + контролі", tooltip: "Шина на ніч, полірування відбудов." },
        },
        metrics: { durabilityScore: 55, speedScore: 78, minInvasiveScore: 90, maintenanceScore: 65, riskScore: 88 },
    },
    veneer_brux: {
        id: "veneer_brux", label: "Вініри", short: "Відновлення естетики при стиранні — нічна шина обов'язкова.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "2–4 тижні", scale: 3, tooltip: "Препарація + лабораторія + фіксація." },
            visits: { value: "2–4", scale: 3, tooltip: "План, препарація, примірка, цементування." },
            durability: { value: "Середньо-висока", scale: 4, tooltip: "Порцеляна стійка, але бруксизм навантажує." },
            invasiveness: { value: "Середня", scale: 3, tooltip: "Обточування — незворотне." },
            risk: { value: "Середній", scale: 3, tooltip: "Без нічної шини зростає ризик перелому. Потрібен контроль." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Стандартна гігієна + нічна шина." },
            worksWhen: ["Помірне стирання з естетичним компонентом", "Бажаєте одночасно відбудувати й захистити", "Приймаєте нічну шину"],
            notIdealWhen: ["Не носите шину — швидше тріснуть", "Виражене стирання — коронка захищає краще", "Стирання лише оклюзійне — відбудов достатньо"],
            maintenance: { value: "Шина + контроль 2×/рік", tooltip: "Обов'язкова нічна шина; регулярний контроль." },
        },
        metrics: { durabilityScore: 72, speedScore: 55, minInvasiveScore: 50, maintenanceScore: 60, riskScore: 52 },
    },
    crown_brux: {
        id: "crown_brux", label: "Коронки", short: "Повне покриття — найкращий захист при вираженому стиранні.",
        icon: "👑", color: "#38bdf8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–21 днів", scale: 3, tooltip: "Протезний цикл: препарація + лабораторія + фіксація." },
            visits: { value: "2–4", scale: 3, tooltip: "Препарація, скан, примірка, цементування." },
            durability: { value: "Висока", scale: 5, tooltip: "Керамічна коронка: 10–20 років. Найстійкіший варіант." },
            invasiveness: { value: "Висока", scale: 1, tooltip: "Значне обточування зубів. Незворотно." },
            risk: { value: "Середній", scale: 3, tooltip: "Може потребувати попереднього ендо. Більше втручання." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Як власні зуби + нічна шина." },
            worksWhen: ["Виражене стирання потребує повної відбудови", "Сильно зруйновані зуби (після ендо, тріщини)", "Бруксизм — коронка найстійкіша"],
            notIdealWhen: ["Раннє стирання — шина + відбудова достатньо", "Бажаєте зберегти максимум тканин", "Зуби в доброму стані — коронки не потрібні"],
            maintenance: { value: "Шина + контроль 2×/рік", tooltip: "Нічна шина обов'язкова. Перевірка герметичності." },
        },
        metrics: { durabilityScore: 85, speedScore: 55, minInvasiveScore: 18, maintenanceScore: 70, riskScore: 50 },
    },
};
