import type { Method } from "./comparatorTypes";

export const METHODS_PERIO: Record<string, Method> = {
    scaling: {
        id: "scaling", label: "Skaling + piaskowanie", short: "Klasyczne usuwanie kamienia + piaskowanie nalotów.",
        icon: "🪥", color: "#10b981", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "1 wizyta (40–60 min)", scale: 5, tooltip: "Jedna sesja higienizacyjna." },
            visits: { value: "1", scale: 5, tooltip: "Jednorazowy zabieg." },
            durability: { value: "Powtarzalne", scale: 2, tooltip: "Efekt 3–6 miesięcy, potem kamień narasta." },
            invasiveness: { value: "Niska", scale: 4, tooltip: "Ultradźwięki + piaskowanie. Może być dyskomfort." },
            risk: { value: "Bardzo niskie", scale: 5, tooltip: "Standardowy zabieg profilaktyczny." },
            hygiene: { value: "Poprawia bazę", scale: 5, tooltip: "Usuwa kamień, ułatwia codzienną higienę." },
            worksWhen: ["Regularna profilaktyka co 6 mies.", "Kamień nad- i poddziąsłowy", "Zapalenie dziąseł (gingivitis)"],
            notIdealWhen: ["Głębokie kieszonki >5 mm — potrzeba kiretażu", "Zaawansowane zapalenie przyzębia", "Wrażliwe dziąsła — rozważ AIRFLOW"],
            maintenance: { value: "Co 6 miesięcy", tooltip: "Regularne wizyty profilaktyczne." },
        },
        metrics: { durabilityScore: 30, speedScore: 95, minInvasiveScore: 75, maintenanceScore: 80, riskScore: 92 },
    },
    airflow: {
        id: "airflow", label: "AIRFLOW (GBT)", short: "Delikatne piaskowanie proszkiem erytrolowym — komfort i precyzja.",
        icon: "💨", color: "#06b6d4", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "1 wizyta (45–60 min)", scale: 5, tooltip: "Pełny protokół GBT w jednej sesji." },
            visits: { value: "1", scale: 5, tooltip: "Jednorazowy zabieg." },
            durability: { value: "Powtarzalne", scale: 2, tooltip: "Efekt 3–6 mies. Regularne powtarzanie." },
            invasiveness: { value: "Bardzo niska", scale: 5, tooltip: "Delikatny proszek erytrytolowy, mniej dyskomfortu." },
            risk: { value: "Bardzo niskie", scale: 5, tooltip: "Bezpieczny nawet na implantach i aparatach." },
            hygiene: { value: "Poprawia bazę", scale: 5, tooltip: "Biofilm usunięty skuteczniej niż tradycyjnie." },
            worksWhen: ["Wrażliwe dziąsła", "Implanty i prace protetyczne", "Aparat ortodontyczny"],
            notIdealWhen: ["Masywny kamień poddziąsłowy — trzeba skaler", "Kieszonki >5 mm — kiretaż", "Szukasz jednorazowego rozwiązania"],
            maintenance: { value: "Co 3–6 miesięcy", tooltip: "Regularne sesje dla optymalnej higieny." },
        },
        metrics: { durabilityScore: 30, speedScore: 92, minInvasiveScore: 92, maintenanceScore: 82, riskScore: 95 },
    },
    curettage: {
        id: "curettage", label: "Kiretaż", short: "Czyszczenie głębokich kieszonek przyzębnych — leczenie, nie profilaktyka.",
        icon: "🩺", color: "#ef4444", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–2 wizyty", scale: 4, tooltip: "Kiretaż zamknięty: 1–2 sesje po kwadrantach." },
            visits: { value: "1–4", scale: 3, tooltip: "Zależy od zakresu (1 kwadrant vs cała jama ustna)." },
            durability: { value: "Lecznicza", scale: 4, tooltip: "Redukcja kieszonek, poprawa przyczepu." },
            invasiveness: { value: "Średnia", scale: 3, tooltip: "Znieczulenie, instrumenty w kieszonkach." },
            risk: { value: "Niskie", scale: 4, tooltip: "Standardowy zabieg periodontologiczny." },
            hygiene: { value: "Wymaga współpracy", scale: 3, tooltip: "Efekt zależy od higieny domowej pacjenta." },
            worksWhen: ["Kieszonki 4–6 mm", "Zapalenie przyzębia (periodontitis)", "Krwawienie z kieszonek mimo dobrej higieny"],
            notIdealWhen: ["Kieszonki <4 mm — skaling wystarczy", "Masywna utrata kości — kiretaż otwarty", "Pacjent nie współpracuje z higieną"],
            maintenance: { value: "Kontrole co 3 mies.", tooltip: "Re-ewaluacja kieszonek po 6–8 tyg." },
        },
        metrics: { durabilityScore: 60, speedScore: 75, minInvasiveScore: 48, maintenanceScore: 55, riskScore: 72 },
    },
    hygiene_instruct: {
        id: "hygiene_instruct", label: "Higienizacja + instruktaż", short: "Skaling + nauka prawidłowej techniki szczotkowania.",
        icon: "📋", color: "#10b981", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "1 wizyta", scale: 5, tooltip: "Higienizacja + 15 min. instruktażu." },
            visits: { value: "1", scale: 5, tooltip: "Jednorazowy zabieg." },
            durability: { value: "Bazowa", scale: 2, tooltip: "Efekt utrzymuje się przy dobrej higieny domowej." },
            invasiveness: { value: "Niska", scale: 5, tooltip: "Skaling + edukacja." },
            risk: { value: "Zerowe", scale: 5, tooltip: "Brak ryzyka." },
            hygiene: { value: "Uczy samodzielności", scale: 5, tooltip: "Instruktaż daje efekty na lata." },
            worksWhen: ["Gingivitis bez kieszonek", "Początek choroby dziąseł", "Pierwsza wizyta od lat"],
            notIdealWhen: ["Kieszonki >4 mm", "Zaawansowana choroba przyzębia", "Kamień poddziąsłowy masywny"],
            maintenance: { value: "Co 6 mies.", tooltip: "Regularne wizyty profilaktyczne." },
        },
        metrics: { durabilityScore: 25, speedScore: 95, minInvasiveScore: 90, maintenanceScore: 88, riskScore: 95 },
    },
    curettage_closed: {
        id: "curettage_closed", label: "Kiretaż zamknięty", short: "Oczyszczenie kieszonek bez odsłaniania płata.",
        icon: "🩹", color: "#f59e0b", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–2 wizyty", scale: 4, tooltip: "Po kwadrantach lub połówkach." },
            visits: { value: "1–2", scale: 4, tooltip: "Znieczulenie + instrumentacja poddziąsłowa." },
            durability: { value: "Dobra", scale: 4, tooltip: "Redukcja kieszonek o 1–2 mm przy współpracy." },
            invasiveness: { value: "Średnia", scale: 3, tooltip: "Znieczulenie, praca w kieszonkach, bez cięcia." },
            risk: { value: "Niskie", scale: 4, tooltip: "Mniej traumatyczny niż otwarty." },
            hygiene: { value: "Wymaga współpracy", scale: 3, tooltip: "Efekt zależy od higieny domowej." },
            worksWhen: ["Kieszonki 4–6 mm", "Umiarkowana utrata kości", "Pierwsza linia leczenia periodontologicznego"],
            notIdealWhen: ["Kieszonki >6 mm", "Skomplikowana anatomia kości", "Brak poprawy po 6–8 tyg."],
            maintenance: { value: "Re-ewaluacja po 6–8 tyg.", tooltip: "Pomiar kieszonek, decyzja o dalszym leczeniu." },
        },
        metrics: { durabilityScore: 58, speedScore: 78, minInvasiveScore: 52, maintenanceScore: 55, riskScore: 75 },
    },
    curettage_open: {
        id: "curettage_open", label: "Kiretaż otwarty", short: "Chirurgiczne odsłonięcie korzeni — dla zaawansowanych kieszonek.",
        icon: "✂️", color: "#ef4444", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1 zabieg + 2 tyg. gojenia", scale: 3, tooltip: "Zabieg chirurgiczny + szwy + gojenie." },
            visits: { value: "2–3", scale: 3, tooltip: "Zabieg, kontrola, zdjęcie szwów." },
            durability: { value: "Wysoka", scale: 4, tooltip: "Lepszy dostęp = dokładniejsze oczyszczenie." },
            invasiveness: { value: "Wysoka", scale: 2, tooltip: "Cięcie, odwarstwienie płata, szwy." },
            risk: { value: "Średnie", scale: 3, tooltip: "Recesja dziąseł po zabiegu." },
            hygiene: { value: "Wymaga współpracy", scale: 3, tooltip: "Krytyczna higiena pooperacyjna." },
            worksWhen: ["Kieszonki >6 mm", "Brak poprawy po kiretażu zamkniętym", "Konieczność augmentacji kostnej"],
            notIdealWhen: ["Kieszonki 4–5 mm — zamknięty wystarczy", "Pacjent nie współpracuje", "Choroby ogólne ograniczające gojenie"],
            maintenance: { value: "Kontrole co 3 mies.", tooltip: "Monitoring przez min. rok." },
        },
        metrics: { durabilityScore: 70, speedScore: 55, minInvasiveScore: 22, maintenanceScore: 50, riskScore: 55 },
    },
    varnish_sensitivity: {
        id: "varnish_sensitivity", label: "Lakier / żel", short: "Aplikacja desensytyzującego preparatu w gabinecie.",
        icon: "💧", color: "#06b6d4", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "1 wizyta (15 min)", scale: 5, tooltip: "Szybka aplikacja na gabinecie." },
            visits: { value: "1–3", scale: 5, tooltip: "Seria 2–3 aplikacji daje najlepszy efekt." },
            durability: { value: "Średnia", scale: 3, tooltip: "Efekt 3–6 mies. Wymaga powtórzeń." },
            invasiveness: { value: "Zerowa", scale: 5, tooltip: "Aplikacja bezbolesna." },
            risk: { value: "Zerowe", scale: 5, tooltip: "Brak ryzyka." },
            hygiene: { value: "Bez zmian", scale: 5, tooltip: "Standardowa higiena." },
            worksWhen: ["Nadwrażliwość po skalingu", "Odsłonięte szyjki zębów", "Szybka ulga potrzebna"],
            notIdealWhen: ["Próchnica jako przyczyna bólu", "Pęknięcie zęba", "Systemowe przyczyny nadwrażliwości"],
            maintenance: { value: "Powtórzenie co 3–6 mies.", tooltip: "Regularne aplikacje wydłużają efekt." },
        },
        metrics: { durabilityScore: 35, speedScore: 95, minInvasiveScore: 100, maintenanceScore: 65, riskScore: 98 },
    },
    laser_sensitivity: {
        id: "laser_sensitivity", label: "Desensytyzacja laserowa", short: "Zamknięcie kanalików zębinowych laserem — skuteczne i trwałe.",
        icon: "⚡", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1 wizyta (20–30 min)", scale: 5, tooltip: "Jedna sesja laserowa." },
            visits: { value: "1–2", scale: 5, tooltip: "Zwykle 1 sesja, czasem powtórzenie." },
            durability: { value: "Dobra", scale: 4, tooltip: "6–12 mies. Trwalsza niż lakiery." },
            invasiveness: { value: "Zerowa", scale: 5, tooltip: "Bezbolesna, bez kontaktu." },
            risk: { value: "Zerowe", scale: 5, tooltip: "Brak ryzyka." },
            hygiene: { value: "Bez zmian", scale: 5, tooltip: "Standardowa higiena." },
            worksWhen: ["Nadwrażliwość oporna na lakiery", "Trwalsza redukcja potrzebna", "Dostępność lasera w gabinecie"],
            notIdealWhen: ["Próchnica jako przyczyna", "Nadwrażliwość łagodna — pasta wystarczy", "Brak dostępu do lasera"],
            maintenance: { value: "1× powtórzenie rocznie", tooltip: "Możliwe powtórzenie po 6–12 mies." },
        },
        metrics: { durabilityScore: 58, speedScore: 90, minInvasiveScore: 100, maintenanceScore: 72, riskScore: 98 },
    },
    paste_sensitivity: {
        id: "paste_sensitivity", label: "Pasta desensytyzująca", short: "Domowa terapia pastą z fluorem/hydroksyapatytem.",
        icon: "🪥", color: "#10b981", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "2–4 tygodnie", scale: 3, tooltip: "Efekt narasta przez 2–4 tyg. stosowania." },
            visits: { value: "0", scale: 5, tooltip: "Samodzielne stosowanie w domu." },
            durability: { value: "Wymaga ciągłości", scale: 2, tooltip: "Efekt utrzymuje się przy codziennym stosowaniu." },
            invasiveness: { value: "Zerowa", scale: 5, tooltip: "Codzienne szczotkowanie pastą." },
            risk: { value: "Zerowe", scale: 5, tooltip: "Brak ryzyka." },
            hygiene: { value: "Integruje się z rutyną", scale: 5, tooltip: "Zamiana pasty — to wszystko." },
            worksWhen: ["Łagodna nadwrażliwość", "Profilaktyka po wybielaniu", "Pierwszy krok terapii"],
            notIdealWhen: ["Silna nadwrażliwość — potrzebna interwencja gabinetowa", "Próchnica lub pęknięcie", "Brak systematyczności"],
            maintenance: { value: "Codzienne stosowanie", tooltip: "Regularność kluczowa dla efektu." },
        },
        metrics: { durabilityScore: 22, speedScore: 50, minInvasiveScore: 100, maintenanceScore: 80, riskScore: 98 },
    },
};
