import type { Method } from "./comparatorTypes";

export const METHODS_KANALOWE_EN: Record<string, Method> = {
    endo_standard: {
        id: "endo_standard", label: "Standard root canal", short: "Manual root canal treatment — effective and proven.",
        icon: "🔧", color: "#f59e0b", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1–3 visits", scale: 4, tooltip: "Depends on the number of canals and complexity." },
            visits: { value: "1–3", scale: 4, tooltip: "Some teeth can be done in 1 visit." },
            durability: { value: "High", scale: 4, tooltip: "Properly treated tooth can last for decades." },
            invasiveness: { value: "Medium", scale: 3, tooltip: "Pulp removal; crown restoration needed." },
            risk: { value: "Low–medium", scale: 4, tooltip: "Risk: missed canal, file fracture, perforation." },
            hygiene: { value: "No change", scale: 5, tooltip: "Standard hygiene after restoration." },
            worksWhen: ["Caries reaching the pulp", "Pulp necrosis", "Preparation for prosthetic crown"],
            notIdealWhen: ["Root fracture — extraction needed", "Tooth not restorable", "Complex anatomy — microscope endo better"],
            maintenance: { value: "Follow-up X-ray", tooltip: "X-ray after 6–12 months, then as needed." },
        },
        metrics: { durabilityScore: 72, speedScore: 72, minInvasiveScore: 40, maintenanceScore: 78, riskScore: 68 },
    },
    endo_microscope: {
        id: "endo_microscope", label: "Microscope root canal", short: "Endo under magnification — precision, safety, higher success.",
        icon: "🔬", color: "#a855f7", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1–2 visits", scale: 4, tooltip: "Microscope allows faster, more precise work." },
            visits: { value: "1–2", scale: 4, tooltip: "Often in 1 visit for single-rooted teeth." },
            durability: { value: "Very high", scale: 5, tooltip: "Success >90%. Better cleaning = fewer retreatments." },
            invasiveness: { value: "Medium", scale: 3, tooltip: "Same procedure as standard endo, but with magnification." },
            risk: { value: "Low", scale: 5, tooltip: "Better visualisation reduces errors." },
            hygiene: { value: "No change", scale: 5, tooltip: "Standard hygiene." },
            worksWhen: ["Complex canal anatomy", "Retreatment of a previous root canal", "Calcified canals, extra canals"],
            notIdealWhen: ["Simple single-canal tooth — standard endo suffices", "Tooth beyond restoring", "Patient doesn't want to invest more"],
            maintenance: { value: "Follow-up X-ray", tooltip: "X-ray after 6–12 months." },
        },
        metrics: { durabilityScore: 88, speedScore: 75, minInvasiveScore: 42, maintenanceScore: 82, riskScore: 82 },
    },
    endo_retreatment: {
        id: "endo_retreatment", label: "Root canal retreatment", short: "Re-treatment of a previously filled canal.",
        icon: "🔄", color: "#ef4444", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "2–3 visits", scale: 3, tooltip: "More time needed: old filling removal + re-cleaning." },
            visits: { value: "2–3", scale: 3, tooltip: "Old material removal, medication, new filling." },
            durability: { value: "Good", scale: 4, tooltip: "Success ~80%. Lower than first-time treatment." },
            invasiveness: { value: "High", scale: 2, tooltip: "Old filling removal may weaken roots." },
            risk: { value: "Medium", scale: 3, tooltip: "Perforation risk, file fracture, canal blockage." },
            hygiene: { value: "No change", scale: 5, tooltip: "Standard hygiene." },
            worksWhen: ["Persistent infection after primary endo", "Periapical lesion on X-ray", "Pain not resolving after prior treatment"],
            notIdealWhen: ["Previous perforation or post — harder to fix", "Root fracture", "Apicoectomy may be simpler"],
            maintenance: { value: "X-ray monitoring", tooltip: "X-ray after 6, 12, 24 months." },
        },
        metrics: { durabilityScore: 68, speedScore: 55, minInvasiveScore: 30, maintenanceScore: 70, riskScore: 55 },
    },
    apicoectomy: {
        id: "apicoectomy", label: "Apicoectomy", short: "Surgical removal of the root apex — last resort to save the tooth.",
        icon: "✂️", color: "#dc2626", recommendedSpecialist: "marcin",
        table: {
            time: { value: "45–90 min", scale: 3, tooltip: "Microsurgical procedure." },
            visits: { value: "2–3", scale: 3, tooltip: "Surgery + check-up + suture removal." },
            durability: { value: "Good", scale: 4, tooltip: "Success ~85–90%. Tooth can be preserved." },
            invasiveness: { value: "High", scale: 2, tooltip: "Surgical access to the root apex." },
            risk: { value: "Medium", scale: 3, tooltip: "Nerve proximity, possible incomplete healing." },
            hygiene: { value: "Wound care", scale: 3, tooltip: "Post-op care: no biting, cold compresses." },
            worksWhen: ["Failed root canal retreatment", "Post in the canal prevents retreatment", "Persistent periapical lesion"],
            notIdealWhen: ["Root canal retreatment possible", "Root fracture", "Tooth not worth saving (prosthetic planning)"],
            maintenance: { value: "X-ray after 6 and 12 months", tooltip: "Healing assessment." },
        },
        metrics: { durabilityScore: 72, speedScore: 55, minInvasiveScore: 15, maintenanceScore: 72, riskScore: 52 },
    },
    vital_pulp: {
        id: "vital_pulp", label: "Vital pulp therapy", short: "Preserving a living pulp — avoiding full root canal.",
        icon: "💚", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 visit", scale: 5, tooltip: "Quick procedure during caries treatment." },
            visits: { value: "1–2", scale: 5, tooltip: "Treatment + check-up." },
            durability: { value: "Medium–high", scale: 4, tooltip: "If successful: tooth stays vital." },
            invasiveness: { value: "Low", scale: 4, tooltip: "Minimal intervention — only affected tissue removed." },
            risk: { value: "Medium", scale: 3, tooltip: "Risk: unsuccessful capping → endo required." },
            hygiene: { value: "No change", scale: 5, tooltip: "Standard hygiene." },
            worksWhen: ["Small/reversible pulp exposure", "Young tooth with immature apex", "Vital pulp with good prognosis"],
            notIdealWhen: ["Irreversible pulpitis — symptoms persist", "Pulp necrosis", "Mature tooth with chronic infection"],
            maintenance: { value: "Follow-up X-ray + vitality test", tooltip: "Monitoring at 3, 6, 12 months." },
        },
        metrics: { durabilityScore: 65, speedScore: 90, minInvasiveScore: 82, maintenanceScore: 68, riskScore: 62 },
    },
};
