import type { Method } from "./comparatorTypes";

export const METHODS_BRAKI_UA: Record<string, Method> = {
    implant: {
        id: "implant", label: "Імплант", short: "Постійна заміна без обточування сусідніх зубів.",
        icon: "🔩", color: "#38bdf8", recommendedSpecialist: "marcin",
        table: {
            time: { value: "3–6 місяців", scale: 2, tooltip: "Встановлення імпланта + загоєння + протезна коронка." },
            visits: { value: "3–5", scale: 3, tooltip: "Консультація, операція, контролі, встановлення коронки." },
            durability: { value: "Висока", scale: 5, tooltip: "Імплант: назавжди. Коронка на імпланті: 10–20 років." },
            invasiveness: { value: "Середня", scale: 3, tooltip: "Хірургічна процедура, але сусідні зуби не зачіпаються." },
            risk: { value: "Середній", scale: 3, tooltip: "Успішність 95–98%. Потрібна хороша гігієна та достатня кістка." },
            hygiene: { value: "Як власний зуб", scale: 4, tooltip: "Звичайне чищення + нитка навколо імпланту." },
            worksWhen: ["Один відсутній зуб зі здоровими сусідами", "Не бажаєте обточувати сусідні зуби", "Достатня кістка або можливість аугментації"],
            notIdealWhen: ["Недостатня кістка без можливості аугментації", "Неконтрольований бруксизм", "Системні захворювання, що обмежують загоєння"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Контрольний знімок, оцінка периімплантних тканин." },
        },
        metrics: { durabilityScore: 92, speedScore: 30, minInvasiveScore: 55, maintenanceScore: 75, riskScore: 68 },
    },
    bridge: {
        id: "bridge", label: "Зубний міст", short: "Незнімна заміна з опорою на сусідні зуби.",
        icon: "🌉", color: "#f59e0b", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–14 днів", scale: 4, tooltip: "Препарація опор, скан/відбитки, лабораторія, фіксація." },
            visits: { value: "2–3", scale: 4, tooltip: "Препарація + фіксація мосту (+можлива примірка)." },
            durability: { value: "Висока", scale: 4, tooltip: "Керамічний міст: 10–15 років. Залежить від стану опор." },
            invasiveness: { value: "Висока", scale: 2, tooltip: "Обточування двох сусідніх зубів." },
            risk: { value: "Середній", scale: 3, tooltip: "Ризик: карієс під коронкою, проблеми опорних зубів." },
            hygiene: { value: "Потребує уваги", scale: 3, tooltip: "Нитка/йоржики під тілом мосту." },
            worksWhen: ["Сусідні зуби вже мають великі пломби/коронки", "Недостатня кістка для імпланту", "Бажаєте результат швидше, ніж імплант"],
            notIdealWhen: ["Сусідні зуби здорові — шкода їх обточувати", "Великий дефект (3+ зубів) — міст може бути задовгий", "Складна гігієна під мостом"],
            maintenance: { value: "Йоржики", tooltip: "Спеціальна гігієна під тілом мосту." },
        },
        metrics: { durabilityScore: 75, speedScore: 75, minInvasiveScore: 25, maintenanceScore: 50, riskScore: 62 },
    },
    partial_denture: {
        id: "partial_denture", label: "Частковий протез", short: "Знімна заміна — швидка та неінвазивна.",
        icon: "🦴", color: "#10b981", recommendedSpecialist: "ilona",
        table: {
            time: { value: "1–3 тижні", scale: 4, tooltip: "Відбитки, примірки, здача." },
            visits: { value: "3–5", scale: 3, tooltip: "Відбитки, прикус, примірка, здача + корекції." },
            durability: { value: "Середня", scale: 3, tooltip: "Протез: 5–10 років. Потрібні перебазування." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Жодного втручання на зубах." },
            risk: { value: "Низький", scale: 5, tooltip: "Без хірургічного ризику. Потрібна адаптація." },
            hygiene: { value: "Потрібна рутина", scale: 3, tooltip: "Зняти, промити, замочити." },
            worksWhen: ["Багато відсутніх зубів", "Не підходите для імплантів/мостів", "Шукаєте найдешевше тимчасове рішення"],
            notIdealWhen: ["Один відсутній зуб — імплант або міст краще", "Не приймаєте знімання протезу", "Молодий, активний пацієнт, що цінує комфорт"],
            maintenance: { value: "Перебазування кожні 2–3 роки", tooltip: "Перебазування, корекції, можлива заміна." },
        },
        metrics: { durabilityScore: 52, speedScore: 70, minInvasiveScore: 95, maintenanceScore: 40, riskScore: 85 },
    },
    implant_immediate: {
        id: "implant_immediate", label: "Негайний імплант", short: "Імплант одразу після видалення зуба.",
        icon: "⚡", color: "#f59e0b", recommendedSpecialist: "marcin",
        table: {
            time: { value: "3–4 місяці", scale: 3, tooltip: "Коротше за відстрочений — загоєння від дня видалення." },
            visits: { value: "3–4", scale: 3, tooltip: "Видалення + імплант, контролі, здача коронки." },
            durability: { value: "Висока", scale: 5, tooltip: "Порівнянна з відстроченим імплантом." },
            invasiveness: { value: "Середня", scale: 3, tooltip: "Одна процедура замість двох. Менше травми." },
            risk: { value: "Середній–вищий", scale: 2, tooltip: "Потрібні ідеальні умови: без інфекції, достатня кістка." },
            hygiene: { value: "Як власний зуб", scale: 4, tooltip: "Стандартна гігієна після загоєння." },
            worksWhen: ["Планове видалення з хорошим станом кістки", "Естетична зона — швидша реабілітація", "Жодного запалення навколо кореня"],
            notIdealWhen: ["Периапікальна інфекція", "Зруйнована кісткова стінка лунки", "Складні анатомічні умови"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Стандартне спостереження за імплантом." },
        },
        metrics: { durabilityScore: 90, speedScore: 55, minInvasiveScore: 58, maintenanceScore: 75, riskScore: 55 },
    },
    implant_delayed: {
        id: "implant_delayed", label: "Відстрочений імплант", short: "Імплант після повного загоєння лунки — безпечніше.",
        icon: "⏳", color: "#38bdf8", recommendedSpecialist: "marcin",
        table: {
            time: { value: "5–9 місяців", scale: 1, tooltip: "3–6 місяців загоєння + 3 місяці остеоінтеграції." },
            visits: { value: "4–6", scale: 2, tooltip: "Видалення, контролі, імплант, контролі, коронка." },
            durability: { value: "Висока", scale: 5, tooltip: "Остеоінтеграція у повністю зрілій кістці." },
            invasiveness: { value: "Загалом вища", scale: 3, tooltip: "Дві окремі хірургічні процедури." },
            risk: { value: "Нижчий", scale: 4, tooltip: "Повний контроль умов. Загоєння перед імплантацією." },
            hygiene: { value: "Як власний зуб", scale: 4, tooltip: "Стандартна гігієна після завершення лікування." },
            worksWhen: ["Запалення навколо кореня", "Втрата кісткової стінки потребує аугментації", "Більш прогнозовані умови загоєння"],
            notIdealWhen: ["Естетична зона — довго без зуба", "Пацієнт очікує швидкий результат", "Ідеальні умови для негайного імпланту"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Стандартне спостереження." },
        },
        metrics: { durabilityScore: 92, speedScore: 20, minInvasiveScore: 50, maintenanceScore: 75, riskScore: 78 },
    },
    bridge_on_teeth: {
        id: "bridge_on_teeth", label: "Міст на зубах", short: "Класичний міст на препарованих опорних зубах.",
        icon: "🌉", color: "#f59e0b", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–14 днів", scale: 4, tooltip: "Швидкий протезний цикл." },
            visits: { value: "2–3", scale: 4, tooltip: "Препарація + фіксація (+примірка)." },
            durability: { value: "Добра", scale: 4, tooltip: "10–15 років при хорошій гігієні." },
            invasiveness: { value: "Висока", scale: 2, tooltip: "Обточування 2+ здорових зубів." },
            risk: { value: "Середній", scale: 3, tooltip: "Опори під загрозою карієсу та втрати вітальності." },
            hygiene: { value: "Потребує уваги", scale: 3, tooltip: "Нитка під тілом мосту." },
            worksWhen: ["Опорні зуби вже відновлені (великі пломби, коронки)", "Немає кістки для імпланту", "Швидке рішення"],
            notIdealWhen: ["Здорові опорні зуби", "Велика протяжність між опорами", "Очікуєте 20+ років без втручання"],
            maintenance: { value: "Нитка + контролі", tooltip: "Спеціальна гігієна під тілом мосту." },
        },
        metrics: { durabilityScore: 72, speedScore: 78, minInvasiveScore: 22, maintenanceScore: 48, riskScore: 60 },
    },
    bridge_on_implants: {
        id: "bridge_on_implants", label: "Міст на імплантах", short: "Міст на імплантах — без обточування власних зубів.",
        icon: "🔩", color: "#38bdf8", recommendedSpecialist: "marcin",
        table: {
            time: { value: "4–8 місяців", scale: 2, tooltip: "Імпланти + загоєння + протезна фаза." },
            visits: { value: "5–8", scale: 2, tooltip: "Консультація, операції, контролі, протезування." },
            durability: { value: "Дуже висока", scale: 5, tooltip: "Імпланти назавжди, міст на імплантах 15–20 років." },
            invasiveness: { value: "Висока", scale: 2, tooltip: "Хірургічні процедури у 2+ ділянках." },
            risk: { value: "Середній", scale: 3, tooltip: "Хірургічний ризик, але власні зуби не зачіпаються." },
            hygiene: { value: "Потребує уваги", scale: 3, tooltip: "Гігієна навколо імплантів + під тілом мосту." },
            worksWhen: ["Кілька суміжних відсутніх зубів", "Бажаєте незнімне рішення без обточування", "Достатня кістка для імплантів"],
            notIdealWhen: ["Недостатня кістка", "Один відсутній зуб — одного імпланту достатньо", "Захворювання, що обмежують загоєння"],
            maintenance: { value: "Контроль 2×/рік", tooltip: "Знімок, оцінка тканин, професійна гігієна." },
        },
        metrics: { durabilityScore: 92, speedScore: 22, minInvasiveScore: 40, maintenanceScore: 55, riskScore: 60 },
    },
    denture_acrylic: {
        id: "denture_acrylic", label: "Акриловий протез", short: "Класичний акриловий протез — найдешевший, але найтовстіший.",
        icon: "📦", color: "#94a3b8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "1–2 тижні", scale: 4, tooltip: "Простий лабораторний процес." },
            visits: { value: "3–4", scale: 4, tooltip: "Відбитки, прикус, примірка, здача." },
            durability: { value: "Середня", scale: 2, tooltip: "3–5 років. Крихкий, може зламатися." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Жодного втручання на зубах." },
            risk: { value: "Низький", scale: 5, tooltip: "Без хірургічного ризику." },
            hygiene: { value: "Проста", scale: 4, tooltip: "Зняти, промити, замочити." },
            worksWhen: ["Тимчасове рішення", "Обмежений бюджет", "Перед запланованими імплантами"],
            notIdealWhen: ["На термін понад 2–3 роки", "Чутливість до об'єму", "Потрібен оптимальний комфорт"],
            maintenance: { value: "Перебазування", tooltip: "Перебазування кожні 1–2 роки." },
        },
        metrics: { durabilityScore: 30, speedScore: 78, minInvasiveScore: 95, maintenanceScore: 45, riskScore: 88 },
    },
    denture_skeletal: {
        id: "denture_skeletal", label: "Бюгельний протез", short: "Металевий каркас — тонший, стабільніший, довговічніший.",
        icon: "⚙️", color: "#38bdf8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "2–4 тижні", scale: 3, tooltip: "Потребує точних примірок." },
            visits: { value: "4–6", scale: 3, tooltip: "Відбитки, примірки, примірка каркасу, здача." },
            durability: { value: "Добра", scale: 4, tooltip: "5–10 років. Довговічніший за акрил." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Кламери спираються на зуби — без обточування." },
            risk: { value: "Низький", scale: 5, tooltip: "Стабільніший, менший ризик перелому." },
            hygiene: { value: "Проста", scale: 4, tooltip: "Зняти, промити. Метал легше чистити." },
            worksWhen: ["Остаточне знімне рішення", "Потрібна стабільність і комфорт", "Є опорні зуби"],
            notIdealWhen: ["Алергія на метал (рідко)", "Естетика: кламери можуть бути видимі", "Немає опорних зубів"],
            maintenance: { value: "Контролі + перебазування", tooltip: "Перебазування кожні 2–3 роки." },
        },
        metrics: { durabilityScore: 58, speedScore: 62, minInvasiveScore: 90, maintenanceScore: 55, riskScore: 85 },
    },
    denture_flexible: {
        id: "denture_flexible", label: "Гнучкий протез", short: "Без металу, естетичні кламери — комфорт і непомітність.",
        icon: "🌿", color: "#10b981", recommendedSpecialist: "ilona",
        table: {
            time: { value: "1–3 тижні", scale: 4, tooltip: "Швидкий лабораторний процес." },
            visits: { value: "3–5", scale: 3, tooltip: "Відбитки, примірки, здача." },
            durability: { value: "Середня", scale: 3, tooltip: "3–5 років. Гнучкий матеріал — не перебазовується." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Жодного втручання на зубах." },
            risk: { value: "Низький", scale: 5, tooltip: "Біосумісний, не алергенний." },
            hygiene: { value: "Потребує уваги", scale: 3, tooltip: "Спеціальні засоби — Valplast легко забарвлюється." },
            worksWhen: ["Малий дефект 1–3 зуби", "Естетика пріоритет — кламери невидимі", "Алергія на метал"],
            notIdealWhen: ["Великий дефект — недостатня стабільність", "Складна гігієна", "Потрібне перебазування (гнучкі не перебазовуються)"],
            maintenance: { value: "Спеціальне чищення", tooltip: "Засоби для Valplast; не шипучі таблетки." },
        },
        metrics: { durabilityScore: 40, speedScore: 72, minInvasiveScore: 95, maintenanceScore: 38, riskScore: 85 },
    },
    full_denture: {
        id: "full_denture", label: "Повний протез", short: "Класичний повний знімний протез.",
        icon: "📋", color: "#94a3b8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "2–4 тижні", scale: 3, tooltip: "Типовий протезний цикл." },
            visits: { value: "4–6", scale: 3, tooltip: "Відбитки, прикусні валики, примірка, здача, корекції." },
            durability: { value: "Середня", scale: 3, tooltip: "5–8 років. Потрібне перебазування при резорбції." },
            invasiveness: { value: "Нульова", scale: 5, tooltip: "Без хірургічного втручання." },
            risk: { value: "Низький", scale: 5, tooltip: "Без хірургічного ризику. Потрібна психологічна адаптація." },
            hygiene: { value: "Рутина", scale: 4, tooltip: "Зняти, промити, замочити. Проста рутина." },
            worksWhen: ["Імплантація неможлива (здоров'я, кістка)", "Обмежений бюджет", "Тимчасове рішення перед імплантами"],
            notIdealWhen: ["Резорбований гребінь — протез погойдується", "Активний спосіб життя — обмежує комфорт їжі", "Імпланти можливі — покривний протез краще"],
            maintenance: { value: "Перебазування кожні 2–3 роки", tooltip: "Перебазування, корекції, оцінка слизової." },
        },
        metrics: { durabilityScore: 48, speedScore: 62, minInvasiveScore: 95, maintenanceScore: 50, riskScore: 90 },
    },
    overdenture: {
        id: "overdenture", label: "Покривний протез на імплантах", short: "Протез на клацання на 2–4 імплантах — стабільний і надійний.",
        icon: "🔩", color: "#38bdf8", recommendedSpecialist: "marcin",
        table: {
            time: { value: "3–6 місяців", scale: 2, tooltip: "Імплантація + протезування." },
            visits: { value: "5–8", scale: 2, tooltip: "Консультація, імпланти, контролі, протезування." },
            durability: { value: "Висока", scale: 5, tooltip: "Імпланти назавжди. Протез із заміною атачменів." },
            invasiveness: { value: "Середня", scale: 3, tooltip: "Хірургічна, але набагато менше, ніж повний міст." },
            risk: { value: "Середній", scale: 3, tooltip: "Хірургічний ризик, але успіх >95%." },
            hygiene: { value: "Проста", scale: 4, tooltip: "Зняти протез; почистити імпланти та протез окремо." },
            worksWhen: ["Беззуба нижня щелепа — різке покращення стабільності", "2 імпланти достатньо для ретенції", "Бажаєте нормально їсти"],
            notIdealWhen: ["Кістка надто резорбована для імплантів", "Системні захворювання проти хірургії", "Очікуєте 100% незнімне рішення"],
            maintenance: { value: "Заміна атачменів + контролі", tooltip: "Атачмени кожні 1–2 роки, контроль кожні 6 місяців." },
        },
        metrics: { durabilityScore: 82, speedScore: 28, minInvasiveScore: 50, maintenanceScore: 55, riskScore: 65 },
    },
    onlay: {
        id: "onlay", label: "Онлей / Інлей", short: "Часткове покриття — зберігає більше тканин, ніж коронка.",
        icon: "🧩", color: "#10b981", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–10 днів", scale: 4, tooltip: "Препарація + скан + лабораторія + цементування." },
            visits: { value: "2", scale: 4, tooltip: "Препарація та здача." },
            durability: { value: "Висока", scale: 5, tooltip: "Керамічний онлей: 10–15 років." },
            invasiveness: { value: "Середня", scale: 4, tooltip: "Менше обточування, ніж коронка — здорові стінки лишаються." },
            risk: { value: "Низький", scale: 4, tooltip: "Більше збережених тканин = менший ризик ускладнень." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Стандартна гігієна." },
            worksWhen: ["Великий дефект, але міцні стінки", "Бажаєте зберегти здорові тканини", "Вітальний зуб без ендо — консервативний підхід"],
            notIdealWhen: ["Зуб після ендо — коронка захищає краще", "Тонкі стінки — зламаються", "Бруксизм з дуже тонкими стінками"],
            maintenance: { value: "Контроль 1×/рік", tooltip: "Оцінка герметичності країв." },
        },
        metrics: { durabilityScore: 82, speedScore: 72, minInvasiveScore: 72, maintenanceScore: 80, riskScore: 78 },
    },
    crown_rebuild: {
        id: "crown_rebuild", label: "Коронка", short: "Повне покриття — максимальний захист для сильно зруйнованого зуба.",
        icon: "👑", color: "#38bdf8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–14 днів", scale: 4, tooltip: "Препарація + лабораторія + фіксація." },
            visits: { value: "2–3", scale: 4, tooltip: "Препарація, примірка, цементування." },
            durability: { value: "Висока", scale: 5, tooltip: "10–20 років. Захищає ослаблений зуб." },
            invasiveness: { value: "Висока", scale: 2, tooltip: "Значне обточування з усіх боків." },
            risk: { value: "Середній", scale: 3, tooltip: "Іноді потрібне попереднє ендо." },
            hygiene: { value: "Легка", scale: 4, tooltip: "Стандартна гігієна + нитка біля країв." },
            worksWhen: ["Зуб після ендо — потребує захисту", "Значна втрата тканин", "Бруксизм — коронка витримує навантаження"],
            notIdealWhen: ["Здорові стінки достатні для онлею", "Бажаєте зберегти максимум тканин", "Немає показань для повного покриття"],
            maintenance: { value: "Контроль 1–2×/рік", tooltip: "Контрольний знімок, оцінка герметичності." },
        },
        metrics: { durabilityScore: 85, speedScore: 70, minInvasiveScore: 25, maintenanceScore: 75, riskScore: 60 },
    },
    composite_rebuild: {
        id: "composite_rebuild", label: "Композитна відбудова", short: "Пряма композитна реставрація — швидка, дешевша, консервативна.",
        icon: "🖌️", color: "#f59e0b", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 візит", scale: 5, tooltip: "Уся реставрація за одну зустріч." },
            visits: { value: "1", scale: 5, tooltip: "Одна процедура." },
            durability: { value: "Середня", scale: 3, tooltip: "3–8 років. Композит може зламатись під великим навантаженням." },
            invasiveness: { value: "Низька", scale: 4, tooltip: "Лише видалення карієсу, збереження здорових тканин." },
            risk: { value: "Низький", scale: 4, tooltip: "Може зламатись при бруксизмі. Легко ремонтується." },
            hygiene: { value: "Легка", scale: 5, tooltip: "Як власний зуб." },
            worksWhen: ["Дефект 30–50% коронки", "Вітальний зуб з хорошим прогнозом", "Швидке рішення, менший бюджет"],
            notIdealWhen: ["Втрата >50% коронки — коронка надійніше", "Зуб після ендо без коронального захисту", "Бруксизм з великими навантаженнями"],
            maintenance: { value: "Контроль 1×/рік", tooltip: "Полірування, оцінка герметичності." },
        },
        metrics: { durabilityScore: 50, speedScore: 95, minInvasiveScore: 82, maintenanceScore: 72, riskScore: 72 },
    },
};
