import type { Method } from "./comparatorTypes";

export const METHODS_ESTETYKA_EN: Record<string, Method> = {
    whitening: {
        id: "whitening", label: "Whitening", short: "Colour change without touching the tooth structure.",
        icon: "🦷", color: "#fbbf24", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "1–14 days", scale: 5, tooltip: "In-office: 1 visit. Take-home trays: 7–14 days." },
            visits: { value: "1–2", scale: 5, tooltip: "One in-office visit or tray delivery + check-up." },
            durability: { value: "Medium", scale: 2, tooltip: "Effect lasts 1–3 years depending on diet and hygiene. Requires touch-ups." },
            invasiveness: { value: "None", scale: 5, tooltip: "No intervention in tooth structure." },
            risk: { value: "Low", scale: 5, tooltip: "Temporary sensitivity. Not for exposed root surfaces." },
            hygiene: { value: "No change", scale: 5, tooltip: "Standard hygiene; avoid staining foods for the first few days." },
            worksWhen: ["You want a brighter shade without grinding", "Teeth are healthy and regular", "The issue is colour only"],
            notIdealWhen: ["You have fillings in the smile zone — they won't whiten", "The issue is shape, not colour", "Severe tooth sensitivity"],
            maintenance: { value: "Touch-up every 1–2 years", tooltip: "Take-home or in-office touch-up." },
        },
        metrics: { durabilityScore: 25, speedScore: 90, minInvasiveScore: 100, maintenanceScore: 60, riskScore: 92 },
    },
    bonding_smile: {
        id: "bonding_smile", label: "Bonding", short: "Direct composite build-up — fast, conservative, reversible.",
        icon: "🖌️", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 day – 2 wks", scale: 5, tooltip: "Simple bonding on 1–2 teeth: 1 visit. Larger scope: 2–3 sessions." },
            visits: { value: "1–3", scale: 5, tooltip: "Often in one session. For 6+ teeth: plan + sessions." },
            durability: { value: "Medium", scale: 3, tooltip: "3–7 years. Composite may stain; requires polishing." },
            invasiveness: { value: "Very low", scale: 5, tooltip: "Minimal or no grinding — material is added." },
            risk: { value: "Low", scale: 5, tooltip: "Reversible procedure. Risk: discolouration or chipping." },
            hygiene: { value: "Easy", scale: 5, tooltip: "Like your own teeth — standard brushing and flossing." },
            worksWhen: ["Minor shape corrections, chips, small gaps", "You want it fast with no grinding", "You want to test a change before veneers"],
            notIdealWhen: ["Major colour changes of the full arch", "Bruxism without a guard", "You expect 10+ year durability with no service"],
            maintenance: { value: "Polishing 1–2×/year", tooltip: "Simple polishing + occasional minor repairs." },
        },
        metrics: { durabilityScore: 45, speedScore: 95, minInvasiveScore: 95, maintenanceScore: 70, riskScore: 90 },
    },
    veneer_porc_smile: {
        id: "veneer_porc_smile", label: "Porcelain veneers", short: "Durable, stain-resistant — the gold standard of aesthetics.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "2–4 weeks", scale: 3, tooltip: "Preparation + scan → lab → cementation." },
            visits: { value: "2–4", scale: 3, tooltip: "Plan, preparation, optional try-in, cementation." },
            durability: { value: "High", scale: 5, tooltip: "Porcelain doesn't change colour. Lifespan 10–20 years." },
            invasiveness: { value: "Medium", scale: 3, tooltip: "0.3–0.7 mm of enamel removed. Irreversible." },
            risk: { value: "Medium", scale: 3, tooltip: "Irreversible grinding. Fracture risk with bruxism." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Porcelain is smooth — easy to clean." },
            worksWhen: ["Full smile makeover of 8–10 teeth", "Major colour and shape change", "Long-term durability is the priority"],
            notIdealWhen: ["You don't want to grind teeth", "1–2 tooth correction — bonding is enough", "Very thin enamel"],
            maintenance: { value: "Check-ups 1–2×/year", tooltip: "Cementation assessment, check teeth under veneers." },
        },
        metrics: { durabilityScore: 88, speedScore: 55, minInvasiveScore: 50, maintenanceScore: 78, riskScore: 60 },
    },
    crown_smile: {
        id: "crown_smile", label: "Crown", short: "Full tooth coverage — restoration + strengthening + aesthetics.",
        icon: "👑", color: "#38bdf8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–14 days", scale: 4, tooltip: "Preparation + scan → lab → cementation." },
            visits: { value: "2–3", scale: 4, tooltip: "Preparation, optional try-in, seating." },
            durability: { value: "High", scale: 5, tooltip: "Ceramic crown: 10–20 years. Protects weakened tooth." },
            invasiveness: { value: "High", scale: 1, tooltip: "Significant tooth reduction on all sides." },
            risk: { value: "Medium", scale: 3, tooltip: "Vitality assessment needed. Sometimes endo first." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Like your own tooth — standard hygiene." },
            worksWhen: ["Heavily damaged tooth (post-endo, large cavities)", "You need strengthening + aesthetics", "Bruxism — crowns are resilient"],
            notIdealWhen: ["Tooth is healthy — a veneer or bonding suffices", "You want to preserve maximum tissue", "Colour-only issue — consider whitening"],
            maintenance: { value: "Check-ups 1–2×/year", tooltip: "Margin seal check, follow-up X-ray." },
        },
        metrics: { durabilityScore: 85, speedScore: 70, minInvasiveScore: 20, maintenanceScore: 75, riskScore: 55 },
    },
    veneer_comp_type: {
        id: "veneer_comp_type", label: "Composite veneers", short: "Faster and less invasive, but require maintenance.",
        icon: "🪞", color: "#f59e0b", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1–7 days", scale: 5, tooltip: "No lab stage. Often in 1–2 visits." },
            visits: { value: "1–2", scale: 5, tooltip: "Plan + treatment session." },
            durability: { value: "Medium", scale: 3, tooltip: "3–7 years. May stain; need polishing." },
            invasiveness: { value: "Low", scale: 4, tooltip: "Minimal grinding — less than porcelain." },
            risk: { value: "Low", scale: 4, tooltip: "Lower durability but procedure is reversible." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Standard hygiene. Avoid hard foods." },
            worksWhen: ["You want a quick result without waiting for the lab", "Compromise: better result than bonding, less invasive than porcelain", "Gap and shape correction"],
            notIdealWhen: ["You expect 10+ year durability", "Bruxism", "Full makeover of 8–10 teeth"],
            maintenance: { value: "Polishing 1–2×/year", tooltip: "Polishing and condition check at follow-ups." },
        },
        metrics: { durabilityScore: 50, speedScore: 88, minInvasiveScore: 80, maintenanceScore: 65, riskScore: 82 },
    },
    veneer_porc_type: {
        id: "veneer_porc_type", label: "Porcelain veneers", short: "Durable, stain-proof, premium — requires the lab.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "2–4 weeks", scale: 3, tooltip: "Preparation → lab → seating." },
            visits: { value: "2–4", scale: 3, tooltip: "Preparation, scan, try-in, cementation." },
            durability: { value: "High", scale: 5, tooltip: "10–20 years. Colour-stable, doesn't stain." },
            invasiveness: { value: "Medium", scale: 3, tooltip: "0.3–0.7 mm grinding. Irreversible." },
            risk: { value: "Medium", scale: 3, tooltip: "Irreversible grinding. Night guard needed with bruxism." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Smooth porcelain — easy to maintain." },
            worksWhen: ["Priority: long-term durability and colour stability", "Full smile makeover", "Major shape and proportion changes"],
            notIdealWhen: ["You want a quick solution", "You don't accept grinding", "1–2 tooth correction"],
            maintenance: { value: "Check-ups 1–2×/year", tooltip: "Cementation and substrate assessment." },
        },
        metrics: { durabilityScore: 88, speedScore: 50, minInvasiveScore: 50, maintenanceScore: 78, riskScore: 60 },
    },
    bonding_spot: {
        id: "bonding_spot", label: "Spot bonding (1–2 teeth)", short: "Quick fix of one or two teeth in a single visit.",
        icon: "✏️", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 visit", scale: 5, tooltip: "Entire procedure in one short appointment." },
            visits: { value: "1", scale: 5, tooltip: "Single 30–60 min session." },
            durability: { value: "Medium", scale: 3, tooltip: "3–7 years. Small repairs are easy." },
            invasiveness: { value: "Minimal", scale: 5, tooltip: "Zero or minimal grinding." },
            risk: { value: "Very low", scale: 5, tooltip: "Fully reversible. Easy to repair." },
            hygiene: { value: "No change", scale: 5, tooltip: "Like your own teeth." },
            worksWhen: ["Chipped corner, minor irregularity", "Small gap between 1–2 teeth", "You want a quick, affordable test of a change"],
            notIdealWhen: ["4+ teeth involved", "You want to change the colour of the entire arch", "You expect multi-year durability"],
            maintenance: { value: "Polishing 1×/year", tooltip: "Quick polishing at check-up." },
        },
        metrics: { durabilityScore: 45, speedScore: 98, minInvasiveScore: 98, maintenanceScore: 75, riskScore: 95 },
    },
    bonding_full: {
        id: "bonding_full", label: "Full-arch bonding (6–10 teeth)", short: "Complete smile change with composite — no lab needed.",
        icon: "😁", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–3 weeks", scale: 4, tooltip: "Planning + 2–3 treatment sessions." },
            visits: { value: "2–4", scale: 4, tooltip: "Plan (DSD/mock-up) + sessions of 3–5 teeth." },
            durability: { value: "Medium", scale: 3, tooltip: "3–7 years. Requires regular servicing." },
            invasiveness: { value: "Low", scale: 4, tooltip: "Minimal grinding, but extensive work." },
            risk: { value: "Low", scale: 4, tooltip: "Reversible. Risk: uneven staining after years." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Standard hygiene. Polishing maintains smoothness." },
            worksWhen: ["You want a makeover without grinding", "Alternative to porcelain veneers", "You want to test a new smile shape"],
            notIdealWhen: ["Bruxism without a guard", "You expect 10+ years with no service", "Very large colour changes"],
            maintenance: { value: "Polishing 2×/year", tooltip: "Regular polishing and margin check." },
        },
        metrics: { durabilityScore: 45, speedScore: 80, minInvasiveScore: 85, maintenanceScore: 60, riskScore: 82 },
    },
    aligners: {
        id: "aligners", label: "Orthodontics (aligners)", short: "Straightening teeth with clear trays — treating the cause, not masking.",
        icon: "🔄", color: "#06b6d4", recommendedSpecialist: "marcin",
        table: {
            time: { value: "6–18 months", scale: 1, tooltip: "Depends on case complexity." },
            visits: { value: "6–12", scale: 1, tooltip: "Check-ups every 4–6 weeks." },
            durability: { value: "Permanent", scale: 5, tooltip: "Lasting result with a retainer." },
            invasiveness: { value: "None", scale: 5, tooltip: "No grinding. Biological movement." },
            risk: { value: "Low", scale: 4, tooltip: "Requires discipline (20+ h/day). Possible root resorption." },
            hygiene: { value: "Needs routine", scale: 3, tooltip: "Remove for eating, clean the trays." },
            worksWhen: ["Crowding, rotations, irregularities", "You want to treat the cause, not mask it", "Gaps due to tooth position"],
            notIdealWhen: ["You want results in a few days", "The issue is colour, not position", "You won't wear trays 20+ h/day"],
            maintenance: { value: "Fixed/removable retainer", tooltip: "Retainer after treatment — key to maintaining the result." },
        },
        metrics: { durabilityScore: 92, speedScore: 15, minInvasiveScore: 95, maintenanceScore: 55, riskScore: 78 },
    },
    bonding_mask: {
        id: "bonding_mask", label: "Bonding / Veneers", short: "Masking irregularities — faster, but doesn't treat the cause.",
        icon: "🎭", color: "#f59e0b", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1–14 days", scale: 5, tooltip: "Bonding: 1 visit. Veneers: 1–2 weeks." },
            visits: { value: "1–3", scale: 5, tooltip: "Plan + treatment session." },
            durability: { value: "Medium", scale: 3, tooltip: "3–10 years depending on material and scope." },
            invasiveness: { value: "Low–medium", scale: 4, tooltip: "Bonding: minimal. Veneers: grinding." },
            risk: { value: "Low", scale: 4, tooltip: "Masking, not positional correction." },
            hygiene: { value: "Easy", scale: 5, tooltip: "Standard hygiene." },
            worksWhen: ["Minor aesthetic irregularities", "You want a quick effect", "You don't accept long orthodontic treatment"],
            notIdealWhen: ["Severe crowding — no room for material", "Bite problems affecting function", "You want a lasting causal solution"],
            maintenance: { value: "Service 1–2×/year", tooltip: "Bonding polishing or veneer check." },
        },
        metrics: { durabilityScore: 50, speedScore: 90, minInvasiveScore: 75, maintenanceScore: 70, riskScore: 82 },
    },
    bonding_dia: {
        id: "bonding_dia", label: "Bonding", short: "Closing a gap with composite — fast and reversible.",
        icon: "🖌️", color: "#10b981", recommendedSpecialist: "katarzyna",
        table: {
            time: { value: "1 visit", scale: 5, tooltip: "Quick gap closure in one session." },
            visits: { value: "1", scale: 5, tooltip: "Entire procedure in one appointment." },
            durability: { value: "Medium", scale: 3, tooltip: "3–7 years. May need adjustments." },
            invasiveness: { value: "None", scale: 5, tooltip: "No grinding." },
            risk: { value: "Very low", scale: 5, tooltip: "Fully reversible." },
            hygiene: { value: "Easy", scale: 5, tooltip: "Flossing requires care at the margins." },
            worksWhen: ["Small gap (1–2 mm)", "You want a quick result", "You want to test before veneers"],
            notIdealWhen: ["Large gap (>3 mm) — may look unnatural", "Gap keeps returning due to tooth position", "Bruxism"],
            maintenance: { value: "Polishing 1×/year", tooltip: "Margin check and polishing." },
        },
        metrics: { durabilityScore: 45, speedScore: 98, minInvasiveScore: 98, maintenanceScore: 72, riskScore: 92 },
    },
    ortho_dia: {
        id: "ortho_dia", label: "Orthodontics", short: "Closing a gap by moving teeth — permanent but slow.",
        icon: "🔄", color: "#06b6d4", recommendedSpecialist: "marcin",
        table: {
            time: { value: "3–12 months", scale: 2, tooltip: "Depends on gap size and compliance." },
            visits: { value: "4–8", scale: 2, tooltip: "Check-ups every 4–6 weeks." },
            durability: { value: "Permanent", scale: 5, tooltip: "Lasting result with a retainer." },
            invasiveness: { value: "None", scale: 5, tooltip: "Biological movement, no grinding." },
            risk: { value: "Low", scale: 4, tooltip: "Requires retainer; otherwise the gap may return." },
            hygiene: { value: "Needs routine", scale: 3, tooltip: "Cleaning with an appliance requires discipline." },
            worksWhen: ["Gap caused by tooth position", "You want a lasting causal solution", "Other irregularities also need correction"],
            notIdealWhen: ["You want an instant effect", "Gap is due to tooth proportions (too narrow)", "You don't accept long treatment"],
            maintenance: { value: "Retainer after treatment", tooltip: "Fixed or removable retainer — essential." },
        },
        metrics: { durabilityScore: 90, speedScore: 20, minInvasiveScore: 95, maintenanceScore: 55, riskScore: 78 },
    },
    veneer_dia: {
        id: "veneer_dia", label: "Veneers", short: "Closing a gap with veneers — lasting with an immediate effect.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–3 weeks", scale: 4, tooltip: "Composite: 1–3 days. Porcelain: 2–3 weeks." },
            visits: { value: "1–3", scale: 4, tooltip: "Depends on material and scope." },
            durability: { value: "Medium–high", scale: 4, tooltip: "Composite: 5–7 years. Porcelain: 10–20 years." },
            invasiveness: { value: "Low–medium", scale: 3, tooltip: "Composite: minimal. Porcelain: grinding." },
            risk: { value: "Low–medium", scale: 4, tooltip: "Porcelain veneers are irreversible." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Standard hygiene + flossing." },
            worksWhen: ["Gap due to tooth proportions", "You also want to improve shape", "You seek a lasting cosmetic result"],
            notIdealWhen: ["Gap due to position — orthodontics is better", "Very large gap (>4 mm)", "You don't want grinding"],
            maintenance: { value: "Check-ups 1–2×/year", tooltip: "Polishing (composite) or check (porcelain)." },
        },
        metrics: { durabilityScore: 72, speedScore: 75, minInvasiveScore: 55, maintenanceScore: 72, riskScore: 72 },
    },
    splint_rebuild: {
        id: "splint_rebuild", label: "Guard + build-ups", short: "Protection from further wear + restoring lost tissue.",
        icon: "🛡️", color: "#10b981", recommendedSpecialist: "ilona",
        table: {
            time: { value: "1–3 weeks", scale: 4, tooltip: "Guard: 1–2 visits. Composite build-ups: 1–3 sessions." },
            visits: { value: "2–4", scale: 4, tooltip: "Guard + build-up sessions." },
            durability: { value: "Medium", scale: 3, tooltip: "Build-ups need servicing. Guard: durable if worn." },
            invasiveness: { value: "Low", scale: 5, tooltip: "Additive build-ups; guard is non-invasive." },
            risk: { value: "Low", scale: 5, tooltip: "Safest approach — protects the remaining teeth." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Guard to clean; teeth as usual." },
            worksWhen: ["Early to moderate wear", "Confirmed bruxism", "You want to protect teeth and gradually rebuild"],
            notIdealWhen: ["Advanced wear requiring full coverage", "You don't wear the guard regularly", "An immediate aesthetic change is the priority"],
            maintenance: { value: "Night guard + check-ups", tooltip: "Wear guard at night, polish build-ups." },
        },
        metrics: { durabilityScore: 55, speedScore: 78, minInvasiveScore: 90, maintenanceScore: 65, riskScore: 88 },
    },
    veneer_brux: {
        id: "veneer_brux", label: "Veneers", short: "Restoring aesthetics after wear — night guard mandatory.",
        icon: "💎", color: "#a855f7", recommendedSpecialist: "marcin",
        table: {
            time: { value: "2–4 weeks", scale: 3, tooltip: "Preparation + lab + seating." },
            visits: { value: "2–4", scale: 3, tooltip: "Plan, preparation, try-in, cementation." },
            durability: { value: "Medium–high", scale: 4, tooltip: "Porcelain is strong, but bruxism is a load." },
            invasiveness: { value: "Medium", scale: 3, tooltip: "Grinding — irreversible." },
            risk: { value: "Medium", scale: 3, tooltip: "Without a night guard fracture risk rises. Follow-up needed." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Standard hygiene + night guard." },
            worksWhen: ["Moderate wear with an aesthetic component", "You want to rebuild and protect at the same time", "You accept a night guard"],
            notIdealWhen: ["You don't wear the guard — they'll fracture sooner", "Advanced wear — a crown protects better", "Occlusal wear only — build-ups suffice"],
            maintenance: { value: "Guard + check-ups 2×/year", tooltip: "Mandatory night guard; regular check-up." },
        },
        metrics: { durabilityScore: 72, speedScore: 55, minInvasiveScore: 50, maintenanceScore: 60, riskScore: 52 },
    },
    crown_brux: {
        id: "crown_brux", label: "Crowns", short: "Full coverage — best protection for advanced wear.",
        icon: "👑", color: "#38bdf8", recommendedSpecialist: "ilona",
        table: {
            time: { value: "5–21 days", scale: 3, tooltip: "Prosthetic cycle: preparation + lab + seating." },
            visits: { value: "2–4", scale: 3, tooltip: "Preparation, scan, try-in, cementation." },
            durability: { value: "High", scale: 5, tooltip: "Ceramic crown: 10–20 years. Most resistant option." },
            invasiveness: { value: "High", scale: 1, tooltip: "Significant tooth reduction. Irreversible." },
            risk: { value: "Medium", scale: 3, tooltip: "May need endo first. Larger intervention." },
            hygiene: { value: "Easy", scale: 4, tooltip: "Like your own teeth + night guard." },
            worksWhen: ["Advanced wear requiring full restoration", "Heavily damaged teeth (post-endo, fractured)", "Bruxism — crown is the most resistant"],
            notIdealWhen: ["Early wear — guard + build-up is enough", "You want to preserve maximum tissue", "Teeth in good condition — no need for crowns"],
            maintenance: { value: "Guard + check-ups 2×/year", tooltip: "Night guard mandatory. Margin seal check." },
        },
        metrics: { durabilityScore: 85, speedScore: 55, minInvasiveScore: 18, maintenanceScore: 70, riskScore: 50 },
    },
};
