import type { Method } from "./comparatorTypes";

export const METHODS_PERIO_EN: Record<string, Method> = {
    scaling: {
        id: "scaling", label: "Scaling", short: "Professional tartar removal — the foundation of periodontal health.",
        icon: "🧹", color: "#38bdf8", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "30–60 min", scale: 5, tooltip: "One appointment. Duration depends on tartar amount." },
            visits: { value: "1", scale: 5, tooltip: "Usually one appointment." },
            durability: { value: "6–12 months", scale: 3, tooltip: "Tartar returns — regular visits needed." },
            invasiveness: { value: "None", scale: 5, tooltip: "Ultrasonic + hand instruments. No grinding." },
            risk: { value: "None", scale: 5, tooltip: "Fully safe. Temporary sensitivity possible." },
            hygiene: { value: "No change", scale: 5, tooltip: "Standard brushing + flossing." },
            worksWhen: ["Tartar and plaque build-up", "Gingivitis (red, bleeding gums)", "Before prosthetic or orthodontic treatment"],
            notIdealWhen: ["Advanced periodontitis — deeper treatment required", "Active abscess — needs drainage first", "Patient expects gum disease will resolve without changed habits"],
            maintenance: { value: "Every 6–12 months", tooltip: "Regular visits maintain results." },
        },
        metrics: { durabilityScore: 40, speedScore: 92, minInvasiveScore: 100, maintenanceScore: 50, riskScore: 100 },
    },
    root_planing: {
        id: "root_planing", label: "Root planing (deep cleaning)", short: "Deep cleaning below the gumline — treating pockets.",
        icon: "🔍", color: "#f59e0b", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "2–4 visits", scale: 3, tooltip: "Quadrant by quadrant under anaesthesia." },
            visits: { value: "2–4", scale: 3, tooltip: "One quadrant per visit with anaesthesia." },
            durability: { value: "Long-term", scale: 4, tooltip: "With good hygiene: lasting pocket reduction." },
            invasiveness: { value: "Low–medium", scale: 4, tooltip: "Under gumline but without a flap." },
            risk: { value: "Low", scale: 4, tooltip: "Temporary sensitivity, possible recession." },
            hygiene: { value: "Crucial", scale: 2, tooltip: "Patient must change habits. Interdental care essential." },
            worksWhen: ["Moderate periodontitis (pockets 4–6 mm)", "First-line treatment after diagnosis", "Patient motivated to change hygiene habits"],
            notIdealWhen: ["Pockets >6 mm — surgical intervention may be needed", "Advanced mobility — prognosis poor", "Patient won't change hygiene habits"],
            maintenance: { value: "Re-evaluation after 6–8 weeks", tooltip: "Pocket re-measurement, hygiene reinforcement." },
        },
        metrics: { durabilityScore: 65, speedScore: 62, minInvasiveScore: 72, maintenanceScore: 58, riskScore: 82 },
    },
    perio_surgery: {
        id: "perio_surgery", label: "Periodontal surgery", short: "Surgical access for deep pocket cleaning.",
        icon: "🔪", color: "#dc2626", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–2 hours", scale: 2, tooltip: "Per surgical segment." },
            visits: { value: "3–5", scale: 3, tooltip: "Surgery + check-ups + suture removal." },
            durability: { value: "Long-term", scale: 4, tooltip: "With good hygiene: bone stabilisation." },
            invasiveness: { value: "High", scale: 2, tooltip: "Flap elevation, cleaning, possibly bone grafts." },
            risk: { value: "Medium", scale: 3, tooltip: "Post-op pain, recession, longer healing." },
            hygiene: { value: "Critical", scale: 2, tooltip: "Strict post-op care and long-term commitment." },
            worksWhen: ["Deep pockets >6 mm not responding to root planing", "Bone loss requiring regeneration", "Tooth worth saving with good prognosis"],
            notIdealWhen: ["Root planing sufficient", "Patient won't maintain hygiene", "Tooth with hopeless prognosis"],
            maintenance: { value: "Supportive periodontal therapy", tooltip: "Check-ups every 3–4 months initially." },
        },
        metrics: { durabilityScore: 72, speedScore: 38, minInvasiveScore: 18, maintenanceScore: 45, riskScore: 55 },
    },
    gum_graft: {
        id: "gum_graft", label: "Gum graft", short: "Covering exposed roots — eliminating sensitivity and recession.",
        icon: "🌱", color: "#10b981", recommendedSpecialist: "marcin",
        table: {
            time: { value: "1–2 hours", scale: 3, tooltip: "Microsurgical procedure." },
            visits: { value: "2–3", scale: 3, tooltip: "Surgery + check-up + suture removal." },
            durability: { value: "Long-term", scale: 4, tooltip: "Good result with proper hygiene." },
            invasiveness: { value: "Medium", scale: 3, tooltip: "Donor site on palate + recipient site." },
            risk: { value: "Medium", scale: 3, tooltip: "Discomfort at donor site, partial graft failure." },
            hygiene: { value: "Careful", scale: 3, tooltip: "Gentle brushing around the graft." },
            worksWhen: ["Recession causing sensitivity or aesthetics issues", "Thin gingival biotype with progressive recession", "Before prosthetics — need attached gingiva"],
            notIdealWhen: ["Very deep recession — limited coverage expected", "Active periodontitis — treat first", "Patient smokes — impairs healing"],
            maintenance: { value: "Soft brushing + check-ups", tooltip: "Avoid trauma. Regular follow-ups." },
        },
        metrics: { durabilityScore: 72, speedScore: 42, minInvasiveScore: 28, maintenanceScore: 62, riskScore: 58 },
    },
    supportive_perio: {
        id: "supportive_perio", label: "Supportive periodontal therapy", short: "Regular maintenance — the key to long-term success.",
        icon: "🔄", color: "#06b6d4", recommendedSpecialist: "malgorzata",
        table: {
            time: { value: "30–45 min", scale: 5, tooltip: "Prophylaxis + pocket assessment." },
            visits: { value: "3–4/year", scale: 2, tooltip: "Every 3–4 months initially." },
            durability: { value: "Ongoing", scale: 5, tooltip: "Continuous support for treated periodontium." },
            invasiveness: { value: "None", scale: 5, tooltip: "Non-invasive maintenance." },
            risk: { value: "None", scale: 5, tooltip: "Safe, preventive procedure." },
            hygiene: { value: "Essential", scale: 2, tooltip: "Patient must maintain home care." },
            worksWhen: ["After active periodontal treatment", "Patient wants to maintain results", "Stable but managed periodontitis"],
            notIdealWhen: ["No prior treatment — not a substitute for active therapy", "Patient non-compliant", "Active periodontal disease needs treatment first"],
            maintenance: { value: "Ongoing 3–4×/year", tooltip: "Lifelong commitment for best results." },
        },
        metrics: { durabilityScore: 82, speedScore: 85, minInvasiveScore: 100, maintenanceScore: 35, riskScore: 100 },
    },
};
