import { NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: Request) {
    try {
        const { image } = await request.json();

        if (!image) {
            return NextResponse.json(
                { error: "No image provided" },
                { status: 400 }
            );
        }

        // Convert base64 to Buffer
        // Expected format: "data:image/png;base64,..."
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");
        const imageBuffer = Buffer.from(base64Data, "base64");

        // Create a File-like object from the buffer (Mocking a File for OpenAI)
        // OpenAI Node SDK expects a File instance or a ReadStream.
        // We'll use a trick or just pass the buffer if supported, but typically it needs 'fs' stream or a File object.
        // Since we are in Next.js Edge/Serverless, we might need a workaround.
        // However, the latest OpenAI SDK supports standard Fetch API 'File'.
        // Let's try creating a File object.

        const file = new File([imageBuffer], "image.png", { type: "image/png" });

        const response = await openai.images.createVariation({
            image: file,
            n: 1,
            size: "1024x1024",
        });

        if (!response || !response.data || !response.data[0]) {
            throw new Error("No image generated by OpenAI");
        }

        const generatedUrl = response.data[0].url;

        return NextResponse.json({ url: generatedUrl });

    } catch (error: any) {
        console.error("OpenAI API Error:", error);

        // Fallback to Mock Mode on Error (e.g. Billing Limit) to keep the app usable for demo
        // We return one of the existing 'after' images as a simulation
        const mockImages = [
            "/metamorphosis_after.jpg",
            "/metamorphosis_2_after.jpg",
            "/metamorphosis_3_after.jpg"
        ];
        const randomMock = mockImages[Math.floor(Math.random() * mockImages.length)];

        return NextResponse.json({
            url: randomMock,
            isMock: true,
            message: "Demonstration Mode (API Limit Reached)"
        });
    }
}
