import { NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: Request) {
    try {
        const formData = await request.formData();
        const imageFile = formData.get("image") as File;
        const maskFile = formData.get("mask") as File;

        if (!imageFile) {
            return NextResponse.json(
                { error: "No image provided" },
                { status: 400 }
            );
        }

        // If mask exists, use it. If not, rely on image transparency (alpha channel)
        // We ALWAYS want to use edit mode for this simulator.
        const response = await openai.images.edit({
            image: imageFile,
            mask: maskFile || undefined,
            prompt: "Make a Hollywood smile. Visible white straight teeth.",
            n: 1,
            size: "1024x1024",
        });


        if (!response || !response.data || !response.data[0]) {
            throw new Error("No image generated by OpenAI");
        }

        return NextResponse.json({ url: response.data[0].url });

    } catch (error: any) {
        console.error("OpenAI API Error:", error);

        // Fallback to Mock Mode on Error (e.g. Billing Limit) to keep the app usable for demo
        // We return one of the existing 'after' images as a simulation
        const mockImages = [
            "/metamorphosis_after.jpg",
            "/metamorphosis_2_after.jpg",
            "/metamorphosis_3_after.jpg"
        ];
        const randomMock = mockImages[Math.floor(Math.random() * mockImages.length)];

        return NextResponse.json({
            url: randomMock,
            isMock: true,
            message: "Demonstration Mode (API Limit Reached)"
        });
    }
}
// Force rebuild timestamp Wed Dec 31 17:46:47 CET 2025
