import { NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: Request) {
    try {
        const { image, mask } = await request.json();

        if (!image) {
            return NextResponse.json(
                { error: "No image provided" },
                { status: 400 }
            );
        }

        // Convert base64 to Buffer
        const base64Data = image.replace(/^data:image\/\w+;base64,/, "");
        const imageBuffer = Buffer.from(base64Data, "base64");

        // Helper to convert Buffer to File object
        const toFile = (buffer: Buffer, filename: string) => {
            return new File([buffer], filename, { type: "image/png" });
        };

        // If mask exists, use Edit Mode
        if (mask) {
            const maskData = mask.replace(/^data:image\/\w+;base64,/, "");
            const maskBuffer = Buffer.from(maskData, "base64");

            const imageFile = toFile(imageBuffer, "image.png");
            const maskFile = toFile(maskBuffer, "mask.png");

            const response = await openai.images.edit({
                image: imageFile,
                mask: maskFile,
                prompt: "A photo of the same person with a perfect, bright, white, straight teeth smile. Photorealistic, natural lighting, high quality dentistry.",
                n: 1,
                size: "1024x1024",
            });

            if (!response || !response.data || !response.data[0]) {
                throw new Error("No image generated by OpenAI");
            }
            return NextResponse.json({ url: response.data[0].url });
        }

        // Fallback to Variation (if no mask) - though frontend sends mask now
        const file = toFile(imageBuffer, "image.png");

        const response = await openai.images.createVariation({
            image: file,
            n: 1,
            size: "1024x1024",
            response_format: "url",
        });

        if (!response || !response.data || !response.data[0]) {
            throw new Error("No image generated by OpenAI");
        }

        const generatedUrl = response.data[0].url;

        return NextResponse.json({ url: generatedUrl });

    } catch (error: any) {
        console.error("OpenAI API Error:", error);

        // Fallback to Mock Mode on Error (e.g. Billing Limit) to keep the app usable for demo
        // We return one of the existing 'after' images as a simulation
        const mockImages = [
            "/metamorphosis_after.jpg",
            "/metamorphosis_2_after.jpg",
            "/metamorphosis_3_after.jpg"
        ];
        const randomMock = mockImages[Math.floor(Math.random() * mockImages.length)];

        return NextResponse.json({
            url: randomMock,
            isMock: true,
            message: "Demonstration Mode (API Limit Reached)"
        });
    }
}
